USE [ENTERPRISE]
GO

/****** Object:  Table [cerner].[ENCNTR_LOC_HIST]    Script Date: 11/29/2021 5:08:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [cerner].[ENCNTR_LOC_HIST](
	[ENCNTR_LOC_HIST_ID] [int] NULL,
	[ENCNTR_ID] [int] NULL,
	[LOCATION_CD] [int] NULL,
	[UPDT_CNT] [int] NULL,
	[UPDT_DT_TM] [datetime2](7) NULL,
	[UPDT_ID] [int] NULL,
	[UPDT_TASK] [int] NULL,
	[UPDT_APPLCTX] [int] NULL,
	[ACTIVE_IND] [int] NULL,
	[ACTIVE_STATUS_CD] [int] NULL,
	[ACTIVE_STATUS_PRSNL_ID] [int] NULL,
	[LOCATION_STATUS_CD] [int] NULL,
	[ARRIVE_PRSNL_ID] [int] NULL,
	[DEPART_PRSNL_ID] [int] NULL,
	[TRANSFER_REASON_CD] [int] NULL,
	[LOCATION_TEMP_IND] [int] NULL,
	[CHART_COMMENT_IND] [int] NULL,
	[COMMENT_TEXT] [varchar](200) NULL,
	[LOC_FACILITY_CD] [int] NULL,
	[LOC_BUILDING_CD] [int] NULL,
	[LOC_NURSE_UNIT_CD] [int] NULL,
	[LOC_ROOM_CD] [int] NULL,
	[LOC_BED_CD] [int] NULL,
	[ENCNTR_TYPE_CD] [int] NULL,
	[MED_SERVICE_CD] [int] NULL,
	[ALT_LVL_CARE_CD] [int] NULL,
	[PROGRAM_SERVICE_CD] [int] NULL,
	[SPECIALTY_UNIT_CD] [int] NULL,
	[PM_HIST_TRACKING_ID] [int] NULL,
	[CHANGE_BIT] [int] NULL,
	[TRACKING_BIT] [int] NULL,
	[ACCOMMODATION_CD] [int] NULL,
	[ACCOMMODATION_REASON_CD] [int] NULL,
	[ACCOMMODATION_REQUEST_CD] [int] NULL,
	[ADMIT_TYPE_CD] [int] NULL,
	[ALC_REASON_CD] [int] NULL,
	[ISOLATION_CD] [int] NULL,
	[ORGANIZATION_ID] [int] NULL,
	[PLACEMENT_AUTH_PRSNL_ID] [int] NULL,
	[SECURITY_ACCESS_CD] [int] NULL,
	[SERVICE_CATEGORY_CD] [int] NULL,
	[ENCNTR_TYPE_CLASS_CD] [int] NULL,
	[TRANSACTION_DT_TM] [datetime2](7) NULL,
	[ACTIVE_STATUS_DT_TM] [datetime2](7) NULL,
	[ACTIVITY_DT_TM] [datetime2](7) NULL,
	[ALT_LVL_CARE_DT_TM] [datetime2](7) NULL,
	[BEG_EFFECTIVE_DT_TM] [datetime2](7) NULL,
	[DEPART_DT_TM] [datetime2](7) NULL,
	[END_EFFECTIVE_DT_TM] [datetime2](7) NULL,
	[ALC_DECOMP_DT_TM] [datetime2](7) NULL,
	[ARRIVE_DT_TM] [datetime2](7) NULL,
	[ENTERPRISE_UPDATE_DT_TM] [datetime2](7) NULL
) ON [PRIMARY]
GO


