USE [ENTERPRISE] 
GO
/****** Object:  StoredProcedure [cerner].[CODE_VALUE_UPDATE]    Script Date: 11/29/2021 5:16:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[CODE_VALUE_UPDATE] AS

BEGIN
	truncate table cerner.CODE_VALUE
END

BEGIN
	INSERT INTO cerner.CODE_VALUE
	EXEC('
	select
		CODE_VALUE
		,CODE_SET
		,CDF_MEANING
		,DISPLAY
		,DISPLAY_KEY
		,DESCRIPTION
		,DEFINITION
		,COLLATION_SEQ
		,ACTIVE_TYPE_CD
		,ACTIVE_IND
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_CNT
		,UPDT_TASK
		,UPDT_APPLCTX
		,DATA_STATUS_CD
		,DATA_STATUS_PRSNL_ID
		,ACTIVE_STATUS_PRSNL_ID
		,CKI
		,DISPLAY_KEY_NLS
		,CONCEPT_CKI
		,ACTIVE_DT_TM
		,BEGIN_EFFECTIVE_DT_TM
		,DATA_STATUS_DT_TM
		,END_EFFECTIVE_DT_TM
		,INACTIVE_DT_TM
		,DISPLAY_KEY_A_NLS
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		code_value
	') AT [CERNERPROD]
END

