USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[ENCNTR_LOC_HIST_UPDATE]    Script Date: 11/29/2021 5:19:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[ENCNTR_LOC_HIST_UPDATE] AS

BEGIN
	create table #encntr_loc_hist_update (
		ENCNTR_LOC_HIST_ID INT
		,ENCNTR_ID INT
		,LOCATION_CD INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,LOCATION_STATUS_CD INT
		,ARRIVE_PRSNL_ID INT
		,DEPART_PRSNL_ID INT
		,TRANSFER_REASON_CD INT
		,LOCATION_TEMP_IND INT
		,CHART_COMMENT_IND INT
		,COMMENT_TEXT VARCHAR(200)
		,LOC_FACILITY_CD INT
		,LOC_BUILDING_CD INT
		,LOC_NURSE_UNIT_CD INT
		,LOC_ROOM_CD INT
		,LOC_BED_CD INT
		,ENCNTR_TYPE_CD INT
		,MED_SERVICE_CD INT
		,ALT_LVL_CARE_CD INT
		,PROGRAM_SERVICE_CD INT
		,SPECIALTY_UNIT_CD INT
		,PM_HIST_TRACKING_ID INT
		,CHANGE_BIT INT
		,TRACKING_BIT INT
		,ACCOMMODATION_CD INT
		,ACCOMMODATION_REASON_CD INT
		,ACCOMMODATION_REQUEST_CD INT
		,ADMIT_TYPE_CD INT
		,ALC_REASON_CD INT
		,ISOLATION_CD INT
		,ORGANIZATION_ID INT
		,PLACEMENT_AUTH_PRSNL_ID INT
		,SECURITY_ACCESS_CD INT
		,SERVICE_CATEGORY_CD INT
		,ENCNTR_TYPE_CLASS_CD INT
		,TRANSACTION_DT_TM DATETIME2
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ACTIVITY_DT_TM DATETIME2
		,ALT_LVL_CARE_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DEPART_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,ALC_DECOMP_DT_TM DATETIME2
		,ARRIVE_DT_TM DATETIME2
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)
	
	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #encntr_loc_hist_update
	EXEC('
	select
		ENCNTR_LOC_HIST_ID
		,ENCNTR_ID
		,LOCATION_CD
		,UPDT_CNT
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_APPLCTX
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,LOCATION_STATUS_CD
		,ARRIVE_PRSNL_ID
		,DEPART_PRSNL_ID
		,TRANSFER_REASON_CD
		,LOCATION_TEMP_IND
		,CHART_COMMENT_IND
		,COMMENT_TEXT
		,LOC_FACILITY_CD
		,LOC_BUILDING_CD
		,LOC_NURSE_UNIT_CD
		,LOC_ROOM_CD
		,LOC_BED_CD
		,ENCNTR_TYPE_CD
		,MED_SERVICE_CD
		,ALT_LVL_CARE_CD
		,PROGRAM_SERVICE_CD
		,SPECIALTY_UNIT_CD
		,PM_HIST_TRACKING_ID
		,CHANGE_BIT
		,TRACKING_BIT
		,ACCOMMODATION_CD
		,ACCOMMODATION_REASON_CD
		,ACCOMMODATION_REQUEST_CD
		,ADMIT_TYPE_CD
		,ALC_REASON_CD
		,ISOLATION_CD
		,ORGANIZATION_ID
		,PLACEMENT_AUTH_PRSNL_ID
		,SECURITY_ACCESS_CD
		,SERVICE_CATEGORY_CD
		,ENCNTR_TYPE_CLASS_CD
		,TRANSACTION_DT_TM
		,ACTIVE_STATUS_DT_TM
		,ACTIVITY_DT_TM
		,ALT_LVL_CARE_DT_TM
		,BEG_EFFECTIVE_DT_TM
		,DEPART_DT_TM
		,END_EFFECTIVE_DT_TM
		,ALC_DECOMP_DT_TM
		,ARRIVE_DT_TM
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		ENCNTR_LOC_HIST
	where
		(updt_dt_tm >= ? and updt_dt_tm < ?)
	', @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	create table #encntr_loc_hist_update_filtered (
		ENCNTR_LOC_HIST_ID INT
		,ENCNTR_ID INT
		,LOCATION_CD INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,LOCATION_STATUS_CD INT
		,ARRIVE_PRSNL_ID INT
		,DEPART_PRSNL_ID INT
		,TRANSFER_REASON_CD INT
		,LOCATION_TEMP_IND INT
		,CHART_COMMENT_IND INT
		,COMMENT_TEXT VARCHAR(200)
		,LOC_FACILITY_CD INT
		,LOC_BUILDING_CD INT
		,LOC_NURSE_UNIT_CD INT
		,LOC_ROOM_CD INT
		,LOC_BED_CD INT
		,ENCNTR_TYPE_CD INT
		,MED_SERVICE_CD INT
		,ALT_LVL_CARE_CD INT
		,PROGRAM_SERVICE_CD INT
		,SPECIALTY_UNIT_CD INT
		,PM_HIST_TRACKING_ID INT
		,CHANGE_BIT INT
		,TRACKING_BIT INT
		,ACCOMMODATION_CD INT
		,ACCOMMODATION_REASON_CD INT
		,ACCOMMODATION_REQUEST_CD INT
		,ADMIT_TYPE_CD INT
		,ALC_REASON_CD INT
		,ISOLATION_CD INT
		,ORGANIZATION_ID INT
		,PLACEMENT_AUTH_PRSNL_ID INT
		,SECURITY_ACCESS_CD INT
		,SERVICE_CATEGORY_CD INT
		,ENCNTR_TYPE_CLASS_CD INT
		,TRANSACTION_DT_TM DATETIME2
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ACTIVITY_DT_TM DATETIME2
		,ALT_LVL_CARE_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DEPART_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,ALC_DECOMP_DT_TM DATETIME2
		,ARRIVE_DT_TM DATETIME2
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #encntr_loc_hist_update_filtered
	select
		eu.ENCNTR_LOC_HIST_ID
		,eu.ENCNTR_ID
		,eu.LOCATION_CD
		,eu.UPDT_CNT
		,eu.UPDT_DT_TM
		,eu.UPDT_ID
		,eu.UPDT_TASK
		,eu.UPDT_APPLCTX
		,eu.ACTIVE_IND
		,eu.ACTIVE_STATUS_CD
		,eu.ACTIVE_STATUS_PRSNL_ID
		,eu.LOCATION_STATUS_CD
		,eu.ARRIVE_PRSNL_ID
		,eu.DEPART_PRSNL_ID
		,eu.TRANSFER_REASON_CD
		,eu.LOCATION_TEMP_IND
		,eu.CHART_COMMENT_IND
		,eu.COMMENT_TEXT
		,eu.LOC_FACILITY_CD
		,eu.LOC_BUILDING_CD
		,eu.LOC_NURSE_UNIT_CD
		,eu.LOC_ROOM_CD
		,eu.LOC_BED_CD
		,eu.ENCNTR_TYPE_CD
		,eu.MED_SERVICE_CD
		,eu.ALT_LVL_CARE_CD
		,eu.PROGRAM_SERVICE_CD
		,eu.SPECIALTY_UNIT_CD
		,eu.PM_HIST_TRACKING_ID
		,eu.CHANGE_BIT
		,eu.TRACKING_BIT
		,eu.ACCOMMODATION_CD
		,eu.ACCOMMODATION_REASON_CD
		,eu.ACCOMMODATION_REQUEST_CD
		,eu.ADMIT_TYPE_CD
		,eu.ALC_REASON_CD
		,eu.ISOLATION_CD
		,eu.ORGANIZATION_ID
		,eu.PLACEMENT_AUTH_PRSNL_ID
		,eu.SECURITY_ACCESS_CD
		,eu.SERVICE_CATEGORY_CD
		,eu.ENCNTR_TYPE_CLASS_CD
		,eu.TRANSACTION_DT_TM
		,eu.ACTIVE_STATUS_DT_TM
		,eu.ACTIVITY_DT_TM
		,eu.ALT_LVL_CARE_DT_TM
		,eu.BEG_EFFECTIVE_DT_TM
		,eu.DEPART_DT_TM
		,eu.END_EFFECTIVE_DT_TM
		,eu.ALC_DECOMP_DT_TM
		,eu.ARRIVE_DT_TM
		,eu.ENTERPRISE_UPDATE_DT_TM
	from
		#encntr_loc_hist_update eu
		left outer join cerner.ENCNTR_LOC_HIST e on e.ENCNTR_LOC_HIST_ID = eu.ENCNTR_LOC_HIST_ID
	where
		e.ENCNTR_LOC_HIST_ID is null
	union all
	select
		eu.ENCNTR_LOC_HIST_ID
		,eu.ENCNTR_ID
		,eu.LOCATION_CD
		,eu.UPDT_CNT
		,eu.UPDT_DT_TM
		,eu.UPDT_ID
		,eu.UPDT_TASK
		,eu.UPDT_APPLCTX
		,eu.ACTIVE_IND
		,eu.ACTIVE_STATUS_CD
		,eu.ACTIVE_STATUS_PRSNL_ID
		,eu.LOCATION_STATUS_CD
		,eu.ARRIVE_PRSNL_ID
		,eu.DEPART_PRSNL_ID
		,eu.TRANSFER_REASON_CD
		,eu.LOCATION_TEMP_IND
		,eu.CHART_COMMENT_IND
		,eu.COMMENT_TEXT
		,eu.LOC_FACILITY_CD
		,eu.LOC_BUILDING_CD
		,eu.LOC_NURSE_UNIT_CD
		,eu.LOC_ROOM_CD
		,eu.LOC_BED_CD
		,eu.ENCNTR_TYPE_CD
		,eu.MED_SERVICE_CD
		,eu.ALT_LVL_CARE_CD
		,eu.PROGRAM_SERVICE_CD
		,eu.SPECIALTY_UNIT_CD
		,eu.PM_HIST_TRACKING_ID
		,eu.CHANGE_BIT
		,eu.TRACKING_BIT
		,eu.ACCOMMODATION_CD
		,eu.ACCOMMODATION_REASON_CD
		,eu.ACCOMMODATION_REQUEST_CD
		,eu.ADMIT_TYPE_CD
		,eu.ALC_REASON_CD
		,eu.ISOLATION_CD
		,eu.ORGANIZATION_ID
		,eu.PLACEMENT_AUTH_PRSNL_ID
		,eu.SECURITY_ACCESS_CD
		,eu.SERVICE_CATEGORY_CD
		,eu.ENCNTR_TYPE_CLASS_CD
		,eu.TRANSACTION_DT_TM
		,eu.ACTIVE_STATUS_DT_TM
		,eu.ACTIVITY_DT_TM
		,eu.ALT_LVL_CARE_DT_TM
		,eu.BEG_EFFECTIVE_DT_TM
		,eu.DEPART_DT_TM
		,eu.END_EFFECTIVE_DT_TM
		,eu.ALC_DECOMP_DT_TM
		,eu.ARRIVE_DT_TM
		,eu.ENTERPRISE_UPDATE_DT_TM
	from
		#encntr_loc_hist_update eu
		left outer join cerner.ENCNTR_LOC_HIST e on e.ENCNTR_LOC_HIST_ID = eu.ENCNTR_LOC_HIST_ID and e.UPDT_CNT < eu.UPDT_CNT
	where
		e.ENCNTR_LOC_HIST_ID is not null
END
		
BEGIN
	delete 
	from 
		cerner.ENCNTR_LOC_HIST
	where 
		ENCNTR_LOC_HIST_ID in (select ENCNTR_LOC_HIST_ID from #encntr_loc_hist_update_filtered)
END

BEGIN
	insert into cerner.ENCNTR_LOC_HIST
	select * from #encntr_loc_hist_update_filtered
END