USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[ENCNTR_ALIAS_UPDATE]    Script Date: 11/29/2021 5:17:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[ENCNTR_ALIAS_UPDATE] AS

BEGIN
	CREATE TABLE #encntr_alias_update (
		ENCNTR_ALIAS_ID INT
		,ENCNTR_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ACTIVE_STATUS_PRSNL_ID INT
		,ALIAS_POOL_CD INT
		,ENCNTR_ALIAS_TYPE_CD INT
		,ALIAS VARCHAR(200)
		,ENCNTR_ALIAS_SUB_TYPE_CD INT
		,CHECK_DIGIT INT
		,CHECK_DIGIT_METHOD_CD INT
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_CD INT
		,DATA_STATUS_DT_TM DATETIME2
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,ASSIGN_AUTHORITY_SYS_CD INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)
	
	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #encntr_alias_update
	EXEC('
	select
		ENCNTR_ALIAS_ID
		,ENCNTR_ID
		,UPDT_CNT
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_APPLCTX
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_DT_TM
		,ACTIVE_STATUS_PRSNL_ID
		,ALIAS_POOL_CD
		,ENCNTR_ALIAS_TYPE_CD
		,ALIAS
		,ENCNTR_ALIAS_SUB_TYPE_CD
		,CHECK_DIGIT
		,CHECK_DIGIT_METHOD_CD
		,BEG_EFFECTIVE_DT_TM
		,END_EFFECTIVE_DT_TM
		,DATA_STATUS_CD
		,DATA_STATUS_DT_TM
		,DATA_STATUS_PRSNL_ID
		,CONTRIBUTOR_SYSTEM_CD
		,ASSIGN_AUTHORITY_SYS_CD
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		encntr_alias
	where
		(updt_dt_tm >= ? and updt_dt_tm < ?)
	', @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	CREATE TABLE #encntr_alias_update_filtered (
		ENCNTR_ALIAS_ID INT
		,ENCNTR_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ACTIVE_STATUS_PRSNL_ID INT
		,ALIAS_POOL_CD INT
		,ENCNTR_ALIAS_TYPE_CD INT
		,ALIAS VARCHAR(200)
		,ENCNTR_ALIAS_SUB_TYPE_CD INT
		,CHECK_DIGIT INT
		,CHECK_DIGIT_METHOD_CD INT
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_CD INT
		,DATA_STATUS_DT_TM DATETIME2
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,ASSIGN_AUTHORITY_SYS_CD INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #encntr_alias_update_filtered
	select
		eu.ENCNTR_ALIAS_ID
		,eu.ENCNTR_ID
		,eu.UPDT_CNT
		,eu.UPDT_DT_TM
		,eu.UPDT_ID
		,eu.UPDT_TASK
		,eu.UPDT_APPLCTX
		,eu.ACTIVE_IND
		,eu.ACTIVE_STATUS_CD
		,eu.ACTIVE_STATUS_DT_TM
		,eu.ACTIVE_STATUS_PRSNL_ID
		,eu.ALIAS_POOL_CD
		,eu.ENCNTR_ALIAS_TYPE_CD
		,eu.ALIAS
		,eu.ENCNTR_ALIAS_SUB_TYPE_CD
		,eu.CHECK_DIGIT
		,eu.CHECK_DIGIT_METHOD_CD
		,eu.BEG_EFFECTIVE_DT_TM
		,eu.END_EFFECTIVE_DT_TM
		,eu.DATA_STATUS_CD
		,eu.DATA_STATUS_DT_TM
		,eu.DATA_STATUS_PRSNL_ID
		,eu.CONTRIBUTOR_SYSTEM_CD
		,eu.ASSIGN_AUTHORITY_SYS_CD
		,eu.ENTERPRISE_UPDATE_DT_TM
	from
		#encntr_alias_update eu
		left outer join cerner.ENCNTR_ALIAS e on e.ENCNTR_ALIAS_ID = eu.ENCNTR_ALIAS_ID
	where
		e.ENCNTR_ALIAS_ID is null
	union all
	select
		eu.ENCNTR_ALIAS_ID
		,eu.ENCNTR_ID
		,eu.UPDT_CNT
		,eu.UPDT_DT_TM
		,eu.UPDT_ID
		,eu.UPDT_TASK
		,eu.UPDT_APPLCTX
		,eu.ACTIVE_IND
		,eu.ACTIVE_STATUS_CD
		,eu.ACTIVE_STATUS_DT_TM
		,eu.ACTIVE_STATUS_PRSNL_ID
		,eu.ALIAS_POOL_CD
		,eu.ENCNTR_ALIAS_TYPE_CD
		,eu.ALIAS
		,eu.ENCNTR_ALIAS_SUB_TYPE_CD
		,eu.CHECK_DIGIT
		,eu.CHECK_DIGIT_METHOD_CD
		,eu.BEG_EFFECTIVE_DT_TM
		,eu.END_EFFECTIVE_DT_TM
		,eu.DATA_STATUS_CD
		,eu.DATA_STATUS_DT_TM
		,eu.DATA_STATUS_PRSNL_ID
		,eu.CONTRIBUTOR_SYSTEM_CD
		,eu.ASSIGN_AUTHORITY_SYS_CD
		,eu.ENTERPRISE_UPDATE_DT_TM
	from
		#encntr_alias_update eu
		left outer join cerner.ENCNTR_ALIAS e on e.ENCNTR_ALIAS_ID = eu.ENCNTR_ALIAS_ID and e.UPDT_CNT < eu.UPDT_CNT
	where
		e.ENCNTR_ALIAS_ID is not null
END
		
BEGIN
	delete 
	from 
		cerner.ENCNTR_ALIAS
	where 
		ENCNTR_ALIAS_ID in (select ENCNTR_ALIAS_ID from #encntr_alias_update_filtered)
END

BEGIN
	insert into cerner.ENCNTR_ALIAS
	select * from #encntr_alias_update_filtered
END