USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[ORDERS_UPDATE]    Script Date: 11/29/2021 5:20:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[ORDERS_UPDATE] AS

BEGIN
	CREATE TABLE #orders_update (
		ORDER_ID BIGINT
		,OE_FORMAT_ID BIGINT
		,ENCNTR_ID BIGINT
		,PERSON_ID BIGINT
		,CATALOG_CD BIGINT
		,SUSPEND_IND BIGINT
		,CONTRIBUTOR_SYSTEM_CD BIGINT
		,CATALOG_TYPE_CD BIGINT
		,ORDER_STATUS_CD BIGINT
		,ORDER_MNEMONIC VARCHAR(100)
		,LAST_ACTION_SEQUENCE BIGINT
		,LAST_UPDATE_PROVIDER_ID BIGINT
		,ACTIVITY_TYPE_CD BIGINT
		,ORDER_DETAIL_DISPLAY_LINE VARCHAR(255)
		,TEMPLATE_ORDER_ID BIGINT
		,TEMPLATE_ORDER_FLAG BIGINT
		,SYNONYM_ID BIGINT
		,LINK_ORDER_FLAG BIGINT
		,LINK_ORDER_ID BIGINT
		,GROUP_ORDER_ID BIGINT
		,GROUP_ORDER_FLAG BIGINT
		,STATUS_PRSNL_ID BIGINT
		,IV_IND BIGINT
		,CONSTANT_IND BIGINT
		,PRN_IND BIGINT
		,ORDER_COMMENT_IND BIGINT
		,NEED_RX_VERIFY_IND BIGINT
		,NEED_NURSE_REVIEW_IND BIGINT
		,NEED_DOCTOR_COSIGN_IND BIGINT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID BIGINT
		,UPDT_TASK BIGINT
		,UPDT_CNT BIGINT
		,UPDT_APPLCTX BIGINT
		,ENCNTR_FINANCIAL_ID BIGINT
		,RESUME_IND BIGINT
		,DISCONTINUE_IND BIGINT
		,PRODUCT_ID BIGINT
		,CS_ORDER_ID BIGINT
		,CS_FLAG BIGINT
		,ACTIVE_STATUS_CD BIGINT
		,ACTIVE_STATUS_PRSNL_ID BIGINT
		,ACTIVE_IND BIGINT
		,HNA_ORDER_MNEMONIC VARCHAR(100)
		,ORIG_ORD_AS_FLAG BIGINT
		,INGREDIENT_IND BIGINT
		,DEPT_STATUS_CD BIGINT
		,REF_TEXT_MASK BIGINT
		,CLINICAL_DISPLAY_LINE VARCHAR(255)
		,DISCONTINUE_TYPE_CD BIGINT
		,RX_MASK BIGINT
		,SCH_STATE_CD BIGINT
		,ORIG_ORDER_CONVS_SEQ BIGINT
		,DCP_CLIN_CAT_CD BIGINT
		,DEPT_MISC_LINE VARCHAR(255)
		,HIDE_FLAG BIGINT
		,INTERVAL_IND BIGINT
		,ORDERABLE_TYPE_FLAG BIGINT
		,CKI VARCHAR(255)
		,NEED_PHYSICIAN_VALIDATE_IND BIGINT
		,MED_ORDER_TYPE_CD BIGINT
		,ORDERED_AS_MNEMONIC VARCHAR(100)
		,INCOMPLETE_ORDER_IND BIGINT
		,LAST_INGRED_ACTION_SEQUENCE BIGINT
		,STOP_TYPE_CD BIGINT
		,TEMPLATE_CORE_ACTION_SEQUENCE BIGINT
		,ESO_NEW_ORDER_IND BIGINT
		,FREQUENCY_ID BIGINT
		,FREQ_TYPE_FLAG BIGINT
		,LAST_CORE_ACTION_SEQUENCE BIGINT
		,COMMENT_TYPE_MASK BIGINT
		,OVERRIDE_FLAG BIGINT
		,REMAINING_DOSE_CNT BIGINT
		,SOFT_STOP_TZ BIGINT
		,PROJECTED_STOP_TZ BIGINT
		,RESUME_EFFECTIVE_TZ BIGINT
		,DISCONTINUE_EFFECTIVE_TZ BIGINT
		,ORIG_ORDER_TZ BIGINT
		,SUSPEND_EFFECTIVE_TZ BIGINT
		,CURRENT_START_TZ BIGINT
		,LINK_TYPE_FLAG BIGINT
		,LINK_NBR FLOAT
		,AD_HOC_ORDER_FLAG BIGINT
		,PATHWAY_CATALOG_ID BIGINT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,INTEREST_DT_TM VARCHAR(100)
		,MODIFIED_START_DT_TM DATETIME2
		,PROJECTED_STOP_DT_TM DATETIME2
		,RESUME_EFFECTIVE_DT_TM DATETIME2
		,SOFT_STOP_DT_TM DATETIME2
		,STATUS_DT_TM DATETIME2
		,VALID_DOSE_DT_TM DATETIME2
		,SUSPEND_EFFECTIVE_DT_TM DATETIME2
		,CURRENT_START_DT_TM DATETIME2
		,DISCONTINUE_EFFECTIVE_DT_TM DATETIME2
		,ORIG_ORDER_DT_TM DATETIME2
		,SIMPLIFIED_DISPLAY_LINE VARCHAR(1000)
		,NEED_RX_CLIN_REVIEW_FLAG BIGINT
		,PRESCRIPTION_ORDER_ID BIGINT
		,SOURCE_CD BIGINT
		,CLIN_RELEVANT_UPDT_DT_TM DATETIME2
		,CLIN_RELEVANT_UPDT_TZ BIGINT
		,IV_SET_SYNONYM_ID BIGINT
		,ORDER_SCHEDULE_PRECISION_BIT BIGINT
		,FUTURE_LOCATION_FACILITY_CD BIGINT
		,FUTURE_LOCATION_NURSE_UNIT_CD BIGINT
		,PRESCRIPTION_GROUP_VALUE BIGINT
		,PROTOCOL_ORDER_ID BIGINT
		,DAY_OF_TREATMENT_SEQUENCE BIGINT
		,FORMULARY_STATUS_CD BIGINT
		,DOSING_METHOD_FLAG BIGINT
		,WARNING_LEVEL_BIT BIGINT
		,TEMPLATE_DOSE_SEQUENCE BIGINT
		,LATEST_COMMUNICATION_TYPE_CD BIGINT
		,ORDER_STATUS_REASON_BIT BIGINT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #orders_update
	EXEC('
	select
		ORDER_ID
		,OE_FORMAT_ID
		,ENCNTR_ID
		,PERSON_ID
		,CATALOG_CD
		,SUSPEND_IND
		,CONTRIBUTOR_SYSTEM_CD
		,CATALOG_TYPE_CD
		,ORDER_STATUS_CD
		,ORDER_MNEMONIC
		,LAST_ACTION_SEQUENCE
		,LAST_UPDATE_PROVIDER_ID
		,ACTIVITY_TYPE_CD
		,ORDER_DETAIL_DISPLAY_LINE
		,TEMPLATE_ORDER_ID
		,TEMPLATE_ORDER_FLAG
		,SYNONYM_ID
		,LINK_ORDER_FLAG
		,LINK_ORDER_ID
		,GROUP_ORDER_ID
		,GROUP_ORDER_FLAG
		,STATUS_PRSNL_ID
		,IV_IND
		,CONSTANT_IND
		,PRN_IND
		,ORDER_COMMENT_IND
		,NEED_RX_VERIFY_IND
		,NEED_NURSE_REVIEW_IND
		,NEED_DOCTOR_COSIGN_IND
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_CNT
		,UPDT_APPLCTX
		,ENCNTR_FINANCIAL_ID
		,RESUME_IND
		,DISCONTINUE_IND
		,PRODUCT_ID
		,CS_ORDER_ID
		,CS_FLAG
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,ACTIVE_IND
		,HNA_ORDER_MNEMONIC
		,ORIG_ORD_AS_FLAG
		,INGREDIENT_IND
		,DEPT_STATUS_CD
		,REF_TEXT_MASK
		,CLINICAL_DISPLAY_LINE
		,DISCONTINUE_TYPE_CD
		,RX_MASK
		,SCH_STATE_CD
		,ORIG_ORDER_CONVS_SEQ
		,DCP_CLIN_CAT_CD
		,DEPT_MISC_LINE
		,HIDE_FLAG
		,INTERVAL_IND
		,ORDERABLE_TYPE_FLAG
		,CKI
		,NEED_PHYSICIAN_VALIDATE_IND
		,MED_ORDER_TYPE_CD
		,ORDERED_AS_MNEMONIC
		,INCOMPLETE_ORDER_IND
		,LAST_INGRED_ACTION_SEQUENCE
		,STOP_TYPE_CD
		,TEMPLATE_CORE_ACTION_SEQUENCE
		,ESO_NEW_ORDER_IND
		,FREQUENCY_ID
		,FREQ_TYPE_FLAG
		,LAST_CORE_ACTION_SEQUENCE
		,COMMENT_TYPE_MASK
		,OVERRIDE_FLAG
		,REMAINING_DOSE_CNT
		,SOFT_STOP_TZ
		,PROJECTED_STOP_TZ
		,RESUME_EFFECTIVE_TZ
		,DISCONTINUE_EFFECTIVE_TZ
		,ORIG_ORDER_TZ
		,SUSPEND_EFFECTIVE_TZ
		,CURRENT_START_TZ
		,LINK_TYPE_FLAG
		,LINK_NBR
		,AD_HOC_ORDER_FLAG
		,PATHWAY_CATALOG_ID
		,ACTIVE_STATUS_DT_TM
		,CAST(INTEREST_DT_TM as VARCHAR(100)) as INTEREST_DT_TM
		,MODIFIED_START_DT_TM
		,PROJECTED_STOP_DT_TM
		,RESUME_EFFECTIVE_DT_TM
		,SOFT_STOP_DT_TM
		,STATUS_DT_TM
		,VALID_DOSE_DT_TM
		,SUSPEND_EFFECTIVE_DT_TM
		,CURRENT_START_DT_TM
		,DISCONTINUE_EFFECTIVE_DT_TM
		,ORIG_ORDER_DT_TM
		,SIMPLIFIED_DISPLAY_LINE
		,NEED_RX_CLIN_REVIEW_FLAG
		,PRESCRIPTION_ORDER_ID
		,SOURCE_CD
		,CLIN_RELEVANT_UPDT_DT_TM
		,CLIN_RELEVANT_UPDT_TZ
		,IV_SET_SYNONYM_ID
		,ORDER_SCHEDULE_PRECISION_BIT
		,FUTURE_LOCATION_FACILITY_CD
		,FUTURE_LOCATION_NURSE_UNIT_CD
		,PRESCRIPTION_GROUP_VALUE
		,PROTOCOL_ORDER_ID
		,DAY_OF_TREATMENT_SEQUENCE
		,FORMULARY_STATUS_CD
		,DOSING_METHOD_FLAG
		,WARNING_LEVEL_BIT
		,TEMPLATE_DOSE_SEQUENCE
		,LATEST_COMMUNICATION_TYPE_CD
		,ORDER_STATUS_REASON_BIT
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		orders
	where
		updt_dt_tm >= ? and updt_dt_tm < ?
	', @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	CREATE TABLE #orders_update_filtered (
		ORDER_ID BIGINT
		,OE_FORMAT_ID BIGINT
		,ENCNTR_ID BIGINT
		,PERSON_ID BIGINT
		,CATALOG_CD BIGINT
		,SUSPEND_IND BIGINT
		,CONTRIBUTOR_SYSTEM_CD BIGINT
		,CATALOG_TYPE_CD BIGINT
		,ORDER_STATUS_CD BIGINT
		,ORDER_MNEMONIC VARCHAR(100)
		,LAST_ACTION_SEQUENCE BIGINT
		,LAST_UPDATE_PROVIDER_ID BIGINT
		,ACTIVITY_TYPE_CD BIGINT
		,ORDER_DETAIL_DISPLAY_LINE VARCHAR(255)
		,TEMPLATE_ORDER_ID BIGINT
		,TEMPLATE_ORDER_FLAG BIGINT
		,SYNONYM_ID BIGINT
		,LINK_ORDER_FLAG BIGINT
		,LINK_ORDER_ID BIGINT
		,GROUP_ORDER_ID BIGINT
		,GROUP_ORDER_FLAG BIGINT
		,STATUS_PRSNL_ID BIGINT
		,IV_IND BIGINT
		,CONSTANT_IND BIGINT
		,PRN_IND BIGINT
		,ORDER_COMMENT_IND BIGINT
		,NEED_RX_VERIFY_IND BIGINT
		,NEED_NURSE_REVIEW_IND BIGINT
		,NEED_DOCTOR_COSIGN_IND BIGINT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID BIGINT
		,UPDT_TASK BIGINT
		,UPDT_CNT BIGINT
		,UPDT_APPLCTX BIGINT
		,ENCNTR_FINANCIAL_ID BIGINT
		,RESUME_IND BIGINT
		,DISCONTINUE_IND BIGINT
		,PRODUCT_ID BIGINT
		,CS_ORDER_ID BIGINT
		,CS_FLAG BIGINT
		,ACTIVE_STATUS_CD BIGINT
		,ACTIVE_STATUS_PRSNL_ID BIGINT
		,ACTIVE_IND BIGINT
		,HNA_ORDER_MNEMONIC VARCHAR(100)
		,ORIG_ORD_AS_FLAG BIGINT
		,INGREDIENT_IND BIGINT
		,DEPT_STATUS_CD BIGINT
		,REF_TEXT_MASK BIGINT
		,CLINICAL_DISPLAY_LINE VARCHAR(255)
		,DISCONTINUE_TYPE_CD BIGINT
		,RX_MASK BIGINT
		,SCH_STATE_CD BIGINT
		,ORIG_ORDER_CONVS_SEQ BIGINT
		,DCP_CLIN_CAT_CD BIGINT
		,DEPT_MISC_LINE VARCHAR(255)
		,HIDE_FLAG BIGINT
		,INTERVAL_IND BIGINT
		,ORDERABLE_TYPE_FLAG BIGINT
		,CKI VARCHAR(255)
		,NEED_PHYSICIAN_VALIDATE_IND BIGINT
		,MED_ORDER_TYPE_CD BIGINT
		,ORDERED_AS_MNEMONIC VARCHAR(100)
		,INCOMPLETE_ORDER_IND BIGINT
		,LAST_INGRED_ACTION_SEQUENCE BIGINT
		,STOP_TYPE_CD BIGINT
		,TEMPLATE_CORE_ACTION_SEQUENCE BIGINT
		,ESO_NEW_ORDER_IND BIGINT
		,FREQUENCY_ID BIGINT
		,FREQ_TYPE_FLAG BIGINT
		,LAST_CORE_ACTION_SEQUENCE BIGINT
		,COMMENT_TYPE_MASK BIGINT
		,OVERRIDE_FLAG BIGINT
		,REMAINING_DOSE_CNT BIGINT
		,SOFT_STOP_TZ BIGINT
		,PROJECTED_STOP_TZ BIGINT
		,RESUME_EFFECTIVE_TZ BIGINT
		,DISCONTINUE_EFFECTIVE_TZ BIGINT
		,ORIG_ORDER_TZ BIGINT
		,SUSPEND_EFFECTIVE_TZ BIGINT
		,CURRENT_START_TZ BIGINT
		,LINK_TYPE_FLAG BIGINT
		,LINK_NBR FLOAT
		,AD_HOC_ORDER_FLAG BIGINT
		,PATHWAY_CATALOG_ID BIGINT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,INTEREST_DT_TM VARCHAR(100)
		,MODIFIED_START_DT_TM DATETIME2
		,PROJECTED_STOP_DT_TM DATETIME2
		,RESUME_EFFECTIVE_DT_TM DATETIME2
		,SOFT_STOP_DT_TM DATETIME2
		,STATUS_DT_TM DATETIME2
		,VALID_DOSE_DT_TM DATETIME2
		,SUSPEND_EFFECTIVE_DT_TM DATETIME2
		,CURRENT_START_DT_TM DATETIME2
		,DISCONTINUE_EFFECTIVE_DT_TM DATETIME2
		,ORIG_ORDER_DT_TM DATETIME2
		,SIMPLIFIED_DISPLAY_LINE VARCHAR(1000)
		,NEED_RX_CLIN_REVIEW_FLAG BIGINT
		,PRESCRIPTION_ORDER_ID BIGINT
		,SOURCE_CD BIGINT
		,CLIN_RELEVANT_UPDT_DT_TM DATETIME2
		,CLIN_RELEVANT_UPDT_TZ BIGINT
		,IV_SET_SYNONYM_ID BIGINT
		,ORDER_SCHEDULE_PRECISION_BIT BIGINT
		,FUTURE_LOCATION_FACILITY_CD BIGINT
		,FUTURE_LOCATION_NURSE_UNIT_CD BIGINT
		,PRESCRIPTION_GROUP_VALUE BIGINT
		,PROTOCOL_ORDER_ID BIGINT
		,DAY_OF_TREATMENT_SEQUENCE BIGINT
		,FORMULARY_STATUS_CD BIGINT
		,DOSING_METHOD_FLAG BIGINT
		,WARNING_LEVEL_BIT BIGINT
		,TEMPLATE_DOSE_SEQUENCE BIGINT
		,LATEST_COMMUNICATION_TYPE_CD BIGINT
		,ORDER_STATUS_REASON_BIT BIGINT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #orders_update_filtered
	select 
		ou.ORDER_ID
		,ou.OE_FORMAT_ID
		,ou.ENCNTR_ID
		,ou.PERSON_ID
		,ou.CATALOG_CD
		,ou.SUSPEND_IND
		,ou.CONTRIBUTOR_SYSTEM_CD
		,ou.CATALOG_TYPE_CD
		,ou.ORDER_STATUS_CD
		,ou.ORDER_MNEMONIC
		,ou.LAST_ACTION_SEQUENCE
		,ou.LAST_UPDATE_PROVIDER_ID
		,ou.ACTIVITY_TYPE_CD
		,ou.ORDER_DETAIL_DISPLAY_LINE
		,ou.TEMPLATE_ORDER_ID
		,ou.TEMPLATE_ORDER_FLAG
		,ou.SYNONYM_ID
		,ou.LINK_ORDER_FLAG
		,ou.LINK_ORDER_ID
		,ou.GROUP_ORDER_ID
		,ou.GROUP_ORDER_FLAG
		,ou.STATUS_PRSNL_ID
		,ou.IV_IND
		,ou.CONSTANT_IND
		,ou.PRN_IND
		,ou.ORDER_COMMENT_IND
		,ou.NEED_RX_VERIFY_IND
		,ou.NEED_NURSE_REVIEW_IND
		,ou.NEED_DOCTOR_COSIGN_IND
		,ou.UPDT_DT_TM
		,ou.UPDT_ID
		,ou.UPDT_TASK
		,ou.UPDT_CNT
		,ou.UPDT_APPLCTX
		,ou.ENCNTR_FINANCIAL_ID
		,ou.RESUME_IND
		,ou.DISCONTINUE_IND
		,ou.PRODUCT_ID
		,ou.CS_ORDER_ID
		,ou.CS_FLAG
		,ou.ACTIVE_STATUS_CD
		,ou.ACTIVE_STATUS_PRSNL_ID
		,ou.ACTIVE_IND
		,ou.HNA_ORDER_MNEMONIC
		,ou.ORIG_ORD_AS_FLAG
		,ou.INGREDIENT_IND
		,ou.DEPT_STATUS_CD
		,ou.REF_TEXT_MASK
		,ou.CLINICAL_DISPLAY_LINE
		,ou.DISCONTINUE_TYPE_CD
		,ou.RX_MASK
		,ou.SCH_STATE_CD
		,ou.ORIG_ORDER_CONVS_SEQ
		,ou.DCP_CLIN_CAT_CD
		,ou.DEPT_MISC_LINE
		,ou.HIDE_FLAG
		,ou.INTERVAL_IND
		,ou.ORDERABLE_TYPE_FLAG
		,ou.CKI
		,ou.NEED_PHYSICIAN_VALIDATE_IND
		,ou.MED_ORDER_TYPE_CD
		,ou.ORDERED_AS_MNEMONIC
		,ou.INCOMPLETE_ORDER_IND
		,ou.LAST_INGRED_ACTION_SEQUENCE
		,ou.STOP_TYPE_CD
		,ou.TEMPLATE_CORE_ACTION_SEQUENCE
		,ou.ESO_NEW_ORDER_IND
		,ou.FREQUENCY_ID
		,ou.FREQ_TYPE_FLAG
		,ou.LAST_CORE_ACTION_SEQUENCE
		,ou.COMMENT_TYPE_MASK
		,ou.OVERRIDE_FLAG
		,ou.REMAINING_DOSE_CNT
		,ou.SOFT_STOP_TZ
		,ou.PROJECTED_STOP_TZ
		,ou.RESUME_EFFECTIVE_TZ
		,ou.DISCONTINUE_EFFECTIVE_TZ
		,ou.ORIG_ORDER_TZ
		,ou.SUSPEND_EFFECTIVE_TZ
		,ou.CURRENT_START_TZ
		,ou.LINK_TYPE_FLAG
		,ou.LINK_NBR
		,ou.AD_HOC_ORDER_FLAG
		,ou.PATHWAY_CATALOG_ID
		,ou.ACTIVE_STATUS_DT_TM
		,ou.INTEREST_DT_TM
		,ou.MODIFIED_START_DT_TM
		,ou.PROJECTED_STOP_DT_TM
		,ou.RESUME_EFFECTIVE_DT_TM
		,ou.SOFT_STOP_DT_TM
		,ou.STATUS_DT_TM
		,ou.VALID_DOSE_DT_TM
		,ou.SUSPEND_EFFECTIVE_DT_TM
		,ou.CURRENT_START_DT_TM
		,ou.DISCONTINUE_EFFECTIVE_DT_TM
		,ou.ORIG_ORDER_DT_TM
		,ou.SIMPLIFIED_DISPLAY_LINE
		,ou.NEED_RX_CLIN_REVIEW_FLAG
		,ou.PRESCRIPTION_ORDER_ID
		,ou.SOURCE_CD
		,ou.CLIN_RELEVANT_UPDT_DT_TM
		,ou.CLIN_RELEVANT_UPDT_TZ
		,ou.IV_SET_SYNONYM_ID
		,ou.ORDER_SCHEDULE_PRECISION_BIT
		,ou.FUTURE_LOCATION_FACILITY_CD
		,ou.FUTURE_LOCATION_NURSE_UNIT_CD
		,ou.PRESCRIPTION_GROUP_VALUE
		,ou.PROTOCOL_ORDER_ID
		,ou.DAY_OF_TREATMENT_SEQUENCE
		,ou.FORMULARY_STATUS_CD
		,ou.DOSING_METHOD_FLAG
		,ou.WARNING_LEVEL_BIT
		,ou.TEMPLATE_DOSE_SEQUENCE
		,ou.LATEST_COMMUNICATION_TYPE_CD
		,ou.ORDER_STATUS_REASON_BIT
		,ou.ENTERPRISE_UPDATE_DT_TM
	from 
		#orders_update ou
		left outer join cerner.ORDERS o on o.ORDER_ID = ou.ORDER_ID
	where
		o.ORDER_ID is null
	union all
	select  
		ou.ORDER_ID
		,ou.OE_FORMAT_ID
		,ou.ENCNTR_ID
		,ou.PERSON_ID
		,ou.CATALOG_CD
		,ou.SUSPEND_IND
		,ou.CONTRIBUTOR_SYSTEM_CD
		,ou.CATALOG_TYPE_CD
		,ou.ORDER_STATUS_CD
		,ou.ORDER_MNEMONIC
		,ou.LAST_ACTION_SEQUENCE
		,ou.LAST_UPDATE_PROVIDER_ID
		,ou.ACTIVITY_TYPE_CD
		,ou.ORDER_DETAIL_DISPLAY_LINE
		,ou.TEMPLATE_ORDER_ID
		,ou.TEMPLATE_ORDER_FLAG
		,ou.SYNONYM_ID
		,ou.LINK_ORDER_FLAG
		,ou.LINK_ORDER_ID
		,ou.GROUP_ORDER_ID
		,ou.GROUP_ORDER_FLAG
		,ou.STATUS_PRSNL_ID
		,ou.IV_IND
		,ou.CONSTANT_IND
		,ou.PRN_IND
		,ou.ORDER_COMMENT_IND
		,ou.NEED_RX_VERIFY_IND
		,ou.NEED_NURSE_REVIEW_IND
		,ou.NEED_DOCTOR_COSIGN_IND
		,ou.UPDT_DT_TM
		,ou.UPDT_ID
		,ou.UPDT_TASK
		,ou.UPDT_CNT
		,ou.UPDT_APPLCTX
		,ou.ENCNTR_FINANCIAL_ID
		,ou.RESUME_IND
		,ou.DISCONTINUE_IND
		,ou.PRODUCT_ID
		,ou.CS_ORDER_ID
		,ou.CS_FLAG
		,ou.ACTIVE_STATUS_CD
		,ou.ACTIVE_STATUS_PRSNL_ID
		,ou.ACTIVE_IND
		,ou.HNA_ORDER_MNEMONIC
		,ou.ORIG_ORD_AS_FLAG
		,ou.INGREDIENT_IND
		,ou.DEPT_STATUS_CD
		,ou.REF_TEXT_MASK
		,ou.CLINICAL_DISPLAY_LINE
		,ou.DISCONTINUE_TYPE_CD
		,ou.RX_MASK
		,ou.SCH_STATE_CD
		,ou.ORIG_ORDER_CONVS_SEQ
		,ou.DCP_CLIN_CAT_CD
		,ou.DEPT_MISC_LINE
		,ou.HIDE_FLAG
		,ou.INTERVAL_IND
		,ou.ORDERABLE_TYPE_FLAG
		,ou.CKI
		,ou.NEED_PHYSICIAN_VALIDATE_IND
		,ou.MED_ORDER_TYPE_CD
		,ou.ORDERED_AS_MNEMONIC
		,ou.INCOMPLETE_ORDER_IND
		,ou.LAST_INGRED_ACTION_SEQUENCE
		,ou.STOP_TYPE_CD
		,ou.TEMPLATE_CORE_ACTION_SEQUENCE
		,ou.ESO_NEW_ORDER_IND
		,ou.FREQUENCY_ID
		,ou.FREQ_TYPE_FLAG
		,ou.LAST_CORE_ACTION_SEQUENCE
		,ou.COMMENT_TYPE_MASK
		,ou.OVERRIDE_FLAG
		,ou.REMAINING_DOSE_CNT
		,ou.SOFT_STOP_TZ
		,ou.PROJECTED_STOP_TZ
		,ou.RESUME_EFFECTIVE_TZ
		,ou.DISCONTINUE_EFFECTIVE_TZ
		,ou.ORIG_ORDER_TZ
		,ou.SUSPEND_EFFECTIVE_TZ
		,ou.CURRENT_START_TZ
		,ou.LINK_TYPE_FLAG
		,ou.LINK_NBR
		,ou.AD_HOC_ORDER_FLAG
		,ou.PATHWAY_CATALOG_ID
		,ou.ACTIVE_STATUS_DT_TM
		,ou.INTEREST_DT_TM
		,ou.MODIFIED_START_DT_TM
		,ou.PROJECTED_STOP_DT_TM
		,ou.RESUME_EFFECTIVE_DT_TM
		,ou.SOFT_STOP_DT_TM
		,ou.STATUS_DT_TM
		,ou.VALID_DOSE_DT_TM
		,ou.SUSPEND_EFFECTIVE_DT_TM
		,ou.CURRENT_START_DT_TM
		,ou.DISCONTINUE_EFFECTIVE_DT_TM
		,ou.ORIG_ORDER_DT_TM
		,ou.SIMPLIFIED_DISPLAY_LINE
		,ou.NEED_RX_CLIN_REVIEW_FLAG
		,ou.PRESCRIPTION_ORDER_ID
		,ou.SOURCE_CD
		,ou.CLIN_RELEVANT_UPDT_DT_TM
		,ou.CLIN_RELEVANT_UPDT_TZ
		,ou.IV_SET_SYNONYM_ID
		,ou.ORDER_SCHEDULE_PRECISION_BIT
		,ou.FUTURE_LOCATION_FACILITY_CD
		,ou.FUTURE_LOCATION_NURSE_UNIT_CD
		,ou.PRESCRIPTION_GROUP_VALUE
		,ou.PROTOCOL_ORDER_ID
		,ou.DAY_OF_TREATMENT_SEQUENCE
		,ou.FORMULARY_STATUS_CD
		,ou.DOSING_METHOD_FLAG
		,ou.WARNING_LEVEL_BIT
		,ou.TEMPLATE_DOSE_SEQUENCE
		,ou.LATEST_COMMUNICATION_TYPE_CD
		,ou.ORDER_STATUS_REASON_BIT
		,ou.ENTERPRISE_UPDATE_DT_TM
	from 
		#orders_update ou
		left outer join cerner.ORDERS o on o.ORDER_ID = ou.ORDER_ID and o.UPDT_CNT < ou.UPDT_CNT
	where
		o.ORDER_ID is not null
END

BEGIN
	delete 
	from 
		cerner.ORDERS
	where 
		ORDER_ID in (select ORDER_ID from #orders_update_filtered)
END

BEGIN
	insert into cerner.ORDERS
	select * from #orders_update_filtered
END

