USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[ORGANIZATION_UPDATE]    Script Date: 11/29/2021 5:21:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[ORGANIZATION_UPDATE] AS

BEGIN
	CREATE TABLE #organization_update (
		ORGANIZATION_ID BIGINT
		,UPDT_CNT BIGINT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID BIGINT
		,UPDT_TASK BIGINT
		,UPDT_APPLCTX BIGINT
		,ACTIVE_IND BIGINT
		,ACTIVE_STATUS_CD BIGINT
		,ACTIVE_STATUS_PRSNL_ID BIGINT
		,DATA_STATUS_CD BIGINT
		,DATA_STATUS_PRSNL_ID BIGINT
		,CONTRIBUTOR_SYSTEM_CD BIGINT
		,ORG_NAME VARCHAR(100)
		,ORG_NAME_KEY VARCHAR(100)
		,FEDERAL_TAX_ID_NBR VARCHAR(100)
		,ORG_STATUS_CD BIGINT
		,FT_ENTITY_ID BIGINT
		,FT_ENTITY_NAME VARCHAR(32)
		,ORG_CLASS_CD BIGINT
		,ORG_NAME_KEY_NLS VARCHAR(202)
		,CONTRIBUTOR_SOURCE_CD BIGINT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,LOGICAL_DOMAIN_ID BIGINT
		,ORG_NAME_KEY_A_NLS VARCHAR(400)
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #organization_update
	EXEC('
	select
		ORGANIZATION_ID
		,UPDT_CNT
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_APPLCTX
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,DATA_STATUS_CD
		,DATA_STATUS_PRSNL_ID
		,CONTRIBUTOR_SYSTEM_CD
		,ORG_NAME
		,ORG_NAME_KEY
		,FEDERAL_TAX_ID_NBR
		,ORG_STATUS_CD
		,FT_ENTITY_ID
		,FT_ENTITY_NAME
		,ORG_CLASS_CD
		,ORG_NAME_KEY_NLS
		,CONTRIBUTOR_SOURCE_CD
		,ACTIVE_STATUS_DT_TM
		,BEG_EFFECTIVE_DT_TM
		,DATA_STATUS_DT_TM
		,END_EFFECTIVE_DT_TM
		,LOGICAL_DOMAIN_ID
		,ORG_NAME_KEY_A_NLS
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		ORGANIZATION
	where
		updt_dt_tm >= ? and updt_dt_tm < ?
	', @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	CREATE TABLE #organization_update_filtered (
		ORGANIZATION_ID BIGINT
		,UPDT_CNT BIGINT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID BIGINT
		,UPDT_TASK BIGINT
		,UPDT_APPLCTX BIGINT
		,ACTIVE_IND BIGINT
		,ACTIVE_STATUS_CD BIGINT
		,ACTIVE_STATUS_PRSNL_ID BIGINT
		,DATA_STATUS_CD BIGINT
		,DATA_STATUS_PRSNL_ID BIGINT
		,CONTRIBUTOR_SYSTEM_CD BIGINT
		,ORG_NAME VARCHAR(100)
		,ORG_NAME_KEY VARCHAR(100)
		,FEDERAL_TAX_ID_NBR VARCHAR(100)
		,ORG_STATUS_CD BIGINT
		,FT_ENTITY_ID BIGINT
		,FT_ENTITY_NAME VARCHAR(32)
		,ORG_CLASS_CD BIGINT
		,ORG_NAME_KEY_NLS VARCHAR(202)
		,CONTRIBUTOR_SOURCE_CD BIGINT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,LOGICAL_DOMAIN_ID BIGINT
		,ORG_NAME_KEY_A_NLS VARCHAR(400)
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #organization_update_filtered
	select 
		ou.ORGANIZATION_ID
		,ou.UPDT_CNT
		,ou.UPDT_DT_TM
		,ou.UPDT_ID
		,ou.UPDT_TASK
		,ou.UPDT_APPLCTX
		,ou.ACTIVE_IND
		,ou.ACTIVE_STATUS_CD
		,ou.ACTIVE_STATUS_PRSNL_ID
		,ou.DATA_STATUS_CD
		,ou.DATA_STATUS_PRSNL_ID
		,ou.CONTRIBUTOR_SYSTEM_CD
		,ou.ORG_NAME
		,ou.ORG_NAME_KEY
		,ou.FEDERAL_TAX_ID_NBR
		,ou.ORG_STATUS_CD
		,ou.FT_ENTITY_ID
		,ou.FT_ENTITY_NAME
		,ou.ORG_CLASS_CD
		,ou.ORG_NAME_KEY_NLS
		,ou.CONTRIBUTOR_SOURCE_CD
		,ou.ACTIVE_STATUS_DT_TM
		,ou.BEG_EFFECTIVE_DT_TM
		,ou.DATA_STATUS_DT_TM
		,ou.END_EFFECTIVE_DT_TM
		,ou.LOGICAL_DOMAIN_ID
		,ou.ORG_NAME_KEY_A_NLS
		,ou.ENTERPRISE_UPDATE_DT_TM
	from 
		#organization_update ou
		left outer join cerner.ORGANIZATION o on o.ORGANIZATION_ID = ou.ORGANIZATION_ID
	where
		o.ORGANIZATION_ID is null
	union all
	select  
		ou.ORGANIZATION_ID
		,ou.UPDT_CNT
		,ou.UPDT_DT_TM
		,ou.UPDT_ID
		,ou.UPDT_TASK
		,ou.UPDT_APPLCTX
		,ou.ACTIVE_IND
		,ou.ACTIVE_STATUS_CD
		,ou.ACTIVE_STATUS_PRSNL_ID
		,ou.DATA_STATUS_CD
		,ou.DATA_STATUS_PRSNL_ID
		,ou.CONTRIBUTOR_SYSTEM_CD
		,ou.ORG_NAME
		,ou.ORG_NAME_KEY
		,ou.FEDERAL_TAX_ID_NBR
		,ou.ORG_STATUS_CD
		,ou.FT_ENTITY_ID
		,ou.FT_ENTITY_NAME
		,ou.ORG_CLASS_CD
		,ou.ORG_NAME_KEY_NLS
		,ou.CONTRIBUTOR_SOURCE_CD
		,ou.ACTIVE_STATUS_DT_TM
		,ou.BEG_EFFECTIVE_DT_TM
		,ou.DATA_STATUS_DT_TM
		,ou.END_EFFECTIVE_DT_TM
		,ou.LOGICAL_DOMAIN_ID
		,ou.ORG_NAME_KEY_A_NLS
		,ou.ENTERPRISE_UPDATE_DT_TM
	from 
		#organization_update ou
		left outer join cerner.ORGANIZATION o on o.ORGANIZATION_ID = ou.ORGANIZATION_ID and o.UPDT_CNT < ou.UPDT_CNT
	where
		o.ORGANIZATION_ID is not null
END

BEGIN
	delete 
	from 
		cerner.ORGANIZATON
	where 
		ORGANIZATION_ID in (select ORGANIZATION_ID from #organization_update_filtered)
END

BEGIN
	insert into cerner.ORGANIZATON
	select * from #organization_update_filtered
END

