USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[PERSON_UPDATE]    Script Date: 11/29/2021 5:21:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[PERSON_UPDATE] AS

BEGIN
	create table #person_update (
		PERSON_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,CREATE_PRSNL_ID INT
		,PERSON_TYPE_CD INT
		,NAME_LAST_KEY VARCHAR(100)
		,NAME_FIRST_KEY VARCHAR(100)
		,NAME_FULL_FORMATTED VARCHAR(100)
		,AUTOPSY_CD INT
		,BIRTH_DT_CD INT
		,CAUSE_OF_DEATH VARCHAR(100)
		,DECEASED_CD INT
		,ETHNIC_GRP_CD INT
		,LANGUAGE_CD INT
		,MARITAL_TYPE_CD INT
		,PURGE_OPTION_CD INT
		,RACE_CD INT
		,RELIGION_CD INT
		,SEX_CD INT
		,SEX_AGE_CHANGE_IND INT
		,DATA_STATUS_CD INT
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,LANGUAGE_DIALECT_CD INT
		,NAME_LAST VARCHAR(200)
		,NAME_FIRST VARCHAR(200)
		,NAME_PHONETIC VARCHAR(8)
		,SPECIES_CD INT
		,CONFID_LEVEL_CD INT
		,VIP_CD INT
		,NAME_FIRST_SYNONYM_ID INT
		,CITIZENSHIP_CD INT
		,VET_MILITARY_STATUS_CD INT
		,MOTHER_MAIDEN_NAME VARCHAR(100)
		,NATIONALITY_CD INT
		,FT_ENTITY_NAME VARCHAR(32)
		,FT_ENTITY_ID INT
		,NAME_MIDDLE_KEY VARCHAR(100)
		,NAME_MIDDLE VARCHAR(200)
		,NAME_FIRST_PHONETIC VARCHAR(8)
		,NAME_LAST_PHONETIC VARCHAR(8)
		,NAME_LAST_KEY_NLS VARCHAR(202)
		,NAME_FIRST_KEY_NLS VARCHAR(202)
		,NAME_MIDDLE_KEY_NLS VARCHAR(202)
		,MILITARY_RANK_CD INT
		,MILITARY_BASE_LOCATION VARCHAR(100)
		,MILITARY_SERVICE_CD INT
		,DECEASED_SOURCE_CD INT
		,CAUSE_OF_DEATH_CD INT
		,BIRTH_TZ INT
		,BIRTH_PREC_FLAG INT
		,ARCHIVE_ENV_ID INT
		,ARCHIVE_STATUS_CD INT
		,ABS_BIRTH_DT_TM DATETIME2
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ARCHIVE_STATUS_DT_TM DATETIME2
		,CONCEPTION_DT_TM DATETIME2
		,CREATE_DT_TM DATETIME2
		,BIRTH_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,NEXT_RESTORE_DT_TM DATETIME2
		,LAST_ENCNTR_DT_TM DATETIME2
		,LAST_ACCESSED_DT_TM DATETIME2
		,DECEASED_DT_TM DATETIME2
		,AGE_AT_DEATH INT
		,AGE_AT_DEATH_UNIT_CD INT
		,AGE_AT_DEATH_PREC_MOD_FLAG INT
		,DECEASED_TZ INT
		,DECEASED_DT_TM_PREC_FLAG INT
		,DECEASED_ID_METHOD_CD INT
		,LOGICAL_DOMAIN_ID INT
		,NAME_LAST_KEY_A_NLS VARCHAR(400)
		,NAME_FIRST_KEY_A_NLS VARCHAR(400)
		,NAME_MIDDLE_KEY_A_NLS VARCHAR(400)
		,PERSON_STATUS_CD INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #person_update
	EXEC('
	select
		PERSON_ID
		,UPDT_CNT
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_APPLCTX
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,CREATE_PRSNL_ID
		,PERSON_TYPE_CD
		,NAME_LAST_KEY
		,NAME_FIRST_KEY
		,NAME_FULL_FORMATTED
		,AUTOPSY_CD
		,BIRTH_DT_CD
		,CAUSE_OF_DEATH
		,DECEASED_CD
		,ETHNIC_GRP_CD
		,LANGUAGE_CD
		,MARITAL_TYPE_CD
		,PURGE_OPTION_CD
		,RACE_CD
		,RELIGION_CD
		,SEX_CD
		,SEX_AGE_CHANGE_IND
		,DATA_STATUS_CD
		,DATA_STATUS_PRSNL_ID
		,CONTRIBUTOR_SYSTEM_CD
		,LANGUAGE_DIALECT_CD
		,NAME_LAST
		,NAME_FIRST
		,NAME_PHONETIC
		,SPECIES_CD
		,CONFID_LEVEL_CD
		,VIP_CD
		,NAME_FIRST_SYNONYM_ID
		,CITIZENSHIP_CD
		,VET_MILITARY_STATUS_CD
		,MOTHER_MAIDEN_NAME
		,NATIONALITY_CD
		,FT_ENTITY_NAME
		,FT_ENTITY_ID
		,NAME_MIDDLE_KEY
		,NAME_MIDDLE
		,NAME_FIRST_PHONETIC
		,NAME_LAST_PHONETIC
		,NAME_LAST_KEY_NLS
		,NAME_FIRST_KEY_NLS
		,NAME_MIDDLE_KEY_NLS
		,MILITARY_RANK_CD
		,MILITARY_BASE_LOCATION
		,MILITARY_SERVICE_CD
		,DECEASED_SOURCE_CD
		,CAUSE_OF_DEATH_CD
		,BIRTH_TZ
		,BIRTH_PREC_FLAG
		,ARCHIVE_ENV_ID
		,ARCHIVE_STATUS_CD
		,ABS_BIRTH_DT_TM
		,ACTIVE_STATUS_DT_TM
		,ARCHIVE_STATUS_DT_TM
		,CONCEPTION_DT_TM
		,CREATE_DT_TM
		,BIRTH_DT_TM
		,BEG_EFFECTIVE_DT_TM
		,DATA_STATUS_DT_TM
		,END_EFFECTIVE_DT_TM
		,NEXT_RESTORE_DT_TM
		,LAST_ENCNTR_DT_TM
		,LAST_ACCESSED_DT_TM
		,DECEASED_DT_TM
		,AGE_AT_DEATH
		,AGE_AT_DEATH_UNIT_CD
		,AGE_AT_DEATH_PREC_MOD_FLAG
		,DECEASED_TZ
		,DECEASED_DT_TM_PREC_FLAG
		,DECEASED_ID_METHOD_CD
		,LOGICAL_DOMAIN_ID
		,NAME_LAST_KEY_A_NLS
		,NAME_FIRST_KEY_A_NLS
		,NAME_MIDDLE_KEY_A_NLS
		,PERSON_STATUS_CD
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		person
	where
		(create_dt_tm >= ? and create_dt_tm < ?)
		OR (updt_dt_tm >= ? and updt_dt_tm < ?)
	', @StartDate, @EndDate, @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	create table #person_update_filtered (
		PERSON_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,CREATE_PRSNL_ID INT
		,PERSON_TYPE_CD INT
		,NAME_LAST_KEY VARCHAR(100)
		,NAME_FIRST_KEY VARCHAR(100)
		,NAME_FULL_FORMATTED VARCHAR(100)
		,AUTOPSY_CD INT
		,BIRTH_DT_CD INT
		,CAUSE_OF_DEATH VARCHAR(100)
		,DECEASED_CD INT
		,ETHNIC_GRP_CD INT
		,LANGUAGE_CD INT
		,MARITAL_TYPE_CD INT
		,PURGE_OPTION_CD INT
		,RACE_CD INT
		,RELIGION_CD INT
		,SEX_CD INT
		,SEX_AGE_CHANGE_IND INT
		,DATA_STATUS_CD INT
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,LANGUAGE_DIALECT_CD INT
		,NAME_LAST VARCHAR(200)
		,NAME_FIRST VARCHAR(200)
		,NAME_PHONETIC VARCHAR(8)
		,SPECIES_CD INT
		,CONFID_LEVEL_CD INT
		,VIP_CD INT
		,NAME_FIRST_SYNONYM_ID INT
		,CITIZENSHIP_CD INT
		,VET_MILITARY_STATUS_CD INT
		,MOTHER_MAIDEN_NAME VARCHAR(100)
		,NATIONALITY_CD INT
		,FT_ENTITY_NAME VARCHAR(32)
		,FT_ENTITY_ID INT
		,NAME_MIDDLE_KEY VARCHAR(100)
		,NAME_MIDDLE VARCHAR(200)
		,NAME_FIRST_PHONETIC VARCHAR(8)
		,NAME_LAST_PHONETIC VARCHAR(8)
		,NAME_LAST_KEY_NLS VARCHAR(202)
		,NAME_FIRST_KEY_NLS VARCHAR(202)
		,NAME_MIDDLE_KEY_NLS VARCHAR(202)
		,MILITARY_RANK_CD INT
		,MILITARY_BASE_LOCATION VARCHAR(100)
		,MILITARY_SERVICE_CD INT
		,DECEASED_SOURCE_CD INT
		,CAUSE_OF_DEATH_CD INT
		,BIRTH_TZ INT
		,BIRTH_PREC_FLAG INT
		,ARCHIVE_ENV_ID INT
		,ARCHIVE_STATUS_CD INT
		,ABS_BIRTH_DT_TM DATETIME2
		,ACTIVE_STATUS_DT_TM DATETIME2
		,ARCHIVE_STATUS_DT_TM DATETIME2
		,CONCEPTION_DT_TM DATETIME2
		,CREATE_DT_TM DATETIME2
		,BIRTH_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,NEXT_RESTORE_DT_TM DATETIME2
		,LAST_ENCNTR_DT_TM DATETIME2
		,LAST_ACCESSED_DT_TM DATETIME2
		,DECEASED_DT_TM DATETIME2
		,AGE_AT_DEATH INT
		,AGE_AT_DEATH_UNIT_CD INT
		,AGE_AT_DEATH_PREC_MOD_FLAG INT
		,DECEASED_TZ INT
		,DECEASED_DT_TM_PREC_FLAG INT
		,DECEASED_ID_METHOD_CD INT
		,LOGICAL_DOMAIN_ID INT
		,NAME_LAST_KEY_A_NLS VARCHAR(400)
		,NAME_FIRST_KEY_A_NLS VARCHAR(400)
		,NAME_MIDDLE_KEY_A_NLS VARCHAR(400)
		,PERSON_STATUS_CD INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #person_update_filtered
	select
		pu.PERSON_ID
		,pu.UPDT_CNT
		,pu.UPDT_DT_TM
		,pu.UPDT_ID
		,pu.UPDT_TASK
		,pu.UPDT_APPLCTX
		,pu.ACTIVE_IND
		,pu.ACTIVE_STATUS_CD
		,pu.ACTIVE_STATUS_PRSNL_ID
		,pu.CREATE_PRSNL_ID
		,pu.PERSON_TYPE_CD
		,pu.NAME_LAST_KEY
		,pu.NAME_FIRST_KEY
		,pu.NAME_FULL_FORMATTED
		,pu.AUTOPSY_CD
		,pu.BIRTH_DT_CD
		,pu.CAUSE_OF_DEATH
		,pu.DECEASED_CD
		,pu.ETHNIC_GRP_CD
		,pu.LANGUAGE_CD
		,pu.MARITAL_TYPE_CD
		,pu.PURGE_OPTION_CD
		,pu.RACE_CD
		,pu.RELIGION_CD
		,pu.SEX_CD
		,pu.SEX_AGE_CHANGE_IND
		,pu.DATA_STATUS_CD
		,pu.DATA_STATUS_PRSNL_ID
		,pu.CONTRIBUTOR_SYSTEM_CD
		,pu.LANGUAGE_DIALECT_CD
		,pu.NAME_LAST
		,pu.NAME_FIRST
		,pu.NAME_PHONETIC
		,pu.SPECIES_CD
		,pu.CONFID_LEVEL_CD
		,pu.VIP_CD
		,pu.NAME_FIRST_SYNONYM_ID
		,pu.CITIZENSHIP_CD
		,pu.VET_MILITARY_STATUS_CD
		,pu.MOTHER_MAIDEN_NAME
		,pu.NATIONALITY_CD
		,pu.FT_ENTITY_NAME
		,pu.FT_ENTITY_ID
		,pu.NAME_MIDDLE_KEY
		,pu.NAME_MIDDLE
		,pu.NAME_FIRST_PHONETIC
		,pu.NAME_LAST_PHONETIC
		,pu.NAME_LAST_KEY_NLS
		,pu.NAME_FIRST_KEY_NLS
		,pu.NAME_MIDDLE_KEY_NLS
		,pu.MILITARY_RANK_CD
		,pu.MILITARY_BASE_LOCATION
		,pu.MILITARY_SERVICE_CD
		,pu.DECEASED_SOURCE_CD
		,pu.CAUSE_OF_DEATH_CD
		,pu.BIRTH_TZ
		,pu.BIRTH_PREC_FLAG
		,pu.ARCHIVE_ENV_ID
		,pu.ARCHIVE_STATUS_CD
		,pu.ABS_BIRTH_DT_TM
		,pu.ACTIVE_STATUS_DT_TM
		,pu.ARCHIVE_STATUS_DT_TM
		,pu.CONCEPTION_DT_TM
		,pu.CREATE_DT_TM
		,pu.BIRTH_DT_TM
		,pu.BEG_EFFECTIVE_DT_TM
		,pu.DATA_STATUS_DT_TM
		,pu.END_EFFECTIVE_DT_TM
		,pu.NEXT_RESTORE_DT_TM
		,pu.LAST_ENCNTR_DT_TM
		,pu.LAST_ACCESSED_DT_TM
		,pu.DECEASED_DT_TM
		,pu.AGE_AT_DEATH
		,pu.AGE_AT_DEATH_UNIT_CD
		,pu.AGE_AT_DEATH_PREC_MOD_FLAG
		,pu.DECEASED_TZ
		,pu.DECEASED_DT_TM_PREC_FLAG
		,pu.DECEASED_ID_METHOD_CD
		,pu.LOGICAL_DOMAIN_ID
		,pu.NAME_LAST_KEY_A_NLS
		,pu.NAME_FIRST_KEY_A_NLS
		,pu.NAME_MIDDLE_KEY_A_NLS
		,pu.PERSON_STATUS_CD
		,pu.ENTERPRISE_UPDATE_DT_TM
	from
		#person_update pu
		left outer join cerner.PERSON p on p.PERSON_ID = pu.PERSON_ID
	where
		p.PERSON_ID is null
	union all
	select
		pu.PERSON_ID
		,pu.UPDT_CNT
		,pu.UPDT_DT_TM
		,pu.UPDT_ID
		,pu.UPDT_TASK
		,pu.UPDT_APPLCTX
		,pu.ACTIVE_IND
		,pu.ACTIVE_STATUS_CD
		,pu.ACTIVE_STATUS_PRSNL_ID
		,pu.CREATE_PRSNL_ID
		,pu.PERSON_TYPE_CD
		,pu.NAME_LAST_KEY
		,pu.NAME_FIRST_KEY
		,pu.NAME_FULL_FORMATTED
		,pu.AUTOPSY_CD
		,pu.BIRTH_DT_CD
		,pu.CAUSE_OF_DEATH
		,pu.DECEASED_CD
		,pu.ETHNIC_GRP_CD
		,pu.LANGUAGE_CD
		,pu.MARITAL_TYPE_CD
		,pu.PURGE_OPTION_CD
		,pu.RACE_CD
		,pu.RELIGION_CD
		,pu.SEX_CD
		,pu.SEX_AGE_CHANGE_IND
		,pu.DATA_STATUS_CD
		,pu.DATA_STATUS_PRSNL_ID
		,pu.CONTRIBUTOR_SYSTEM_CD
		,pu.LANGUAGE_DIALECT_CD
		,pu.NAME_LAST
		,pu.NAME_FIRST
		,pu.NAME_PHONETIC
		,pu.SPECIES_CD
		,pu.CONFID_LEVEL_CD
		,pu.VIP_CD
		,pu.NAME_FIRST_SYNONYM_ID
		,pu.CITIZENSHIP_CD
		,pu.VET_MILITARY_STATUS_CD
		,pu.MOTHER_MAIDEN_NAME
		,pu.NATIONALITY_CD
		,pu.FT_ENTITY_NAME
		,pu.FT_ENTITY_ID
		,pu.NAME_MIDDLE_KEY
		,pu.NAME_MIDDLE
		,pu.NAME_FIRST_PHONETIC
		,pu.NAME_LAST_PHONETIC
		,pu.NAME_LAST_KEY_NLS
		,pu.NAME_FIRST_KEY_NLS
		,pu.NAME_MIDDLE_KEY_NLS
		,pu.MILITARY_RANK_CD
		,pu.MILITARY_BASE_LOCATION
		,pu.MILITARY_SERVICE_CD
		,pu.DECEASED_SOURCE_CD
		,pu.CAUSE_OF_DEATH_CD
		,pu.BIRTH_TZ
		,pu.BIRTH_PREC_FLAG
		,pu.ARCHIVE_ENV_ID
		,pu.ARCHIVE_STATUS_CD
		,pu.ABS_BIRTH_DT_TM
		,pu.ACTIVE_STATUS_DT_TM
		,pu.ARCHIVE_STATUS_DT_TM
		,pu.CONCEPTION_DT_TM
		,pu.CREATE_DT_TM
		,pu.BIRTH_DT_TM
		,pu.BEG_EFFECTIVE_DT_TM
		,pu.DATA_STATUS_DT_TM
		,pu.END_EFFECTIVE_DT_TM
		,pu.NEXT_RESTORE_DT_TM
		,pu.LAST_ENCNTR_DT_TM
		,pu.LAST_ACCESSED_DT_TM
		,pu.DECEASED_DT_TM
		,pu.AGE_AT_DEATH
		,pu.AGE_AT_DEATH_UNIT_CD
		,pu.AGE_AT_DEATH_PREC_MOD_FLAG
		,pu.DECEASED_TZ
		,pu.DECEASED_DT_TM_PREC_FLAG
		,pu.DECEASED_ID_METHOD_CD
		,pu.LOGICAL_DOMAIN_ID
		,pu.NAME_LAST_KEY_A_NLS
		,pu.NAME_FIRST_KEY_A_NLS
		,pu.NAME_MIDDLE_KEY_A_NLS
		,pu.PERSON_STATUS_CD
		,pu.ENTERPRISE_UPDATE_DT_TM
	from
		#person_update pu
		left outer join cerner.PERSON p on p.PERSON_ID = pu.PERSON_ID and p.UPDT_CNT < pu.UPDT_CNT
	where
		p.PERSON_ID is not null
END

BEGIN
	delete 
	from 
		cerner.PERSON
	where 
		PERSON_ID in (select PERSON_ID from #person_update_filtered)
END

BEGIN
	insert into cerner.PERSON
	select * from #person_update_filtered
END

