USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[PRSNL_UPDATE]    Script Date: 11/29/2021 5:22:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[PRSNL_UPDATE] AS

BEGIN
	CREATE TABLE #prsnl_update (
		PERSON_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,CREATE_PRSNL_ID INT
		,NAME_LAST_KEY VARCHAR(100)
		,NAME_FIRST_KEY VARCHAR(100)
		,PRSNL_TYPE_CD INT
		,NAME_FULL_FORMATTED VARCHAR(100)
		,PASSWORD VARCHAR(100)
		,EMAIL VARCHAR(100)
		,PHYSICIAN_IND INT
		,POSITION_CD INT
		,DEPARTMENT_CD INT
		,FREE_TEXT_IND INT
		,SECTION_CD INT
		,DATA_STATUS_CD INT
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,NAME_LAST VARCHAR(200)
		,NAME_FIRST VARCHAR(200)
		,USERNAME VARCHAR(50)
		,FT_ENTITY_NAME VARCHAR(32)
		,FT_ENTITY_ID INT
		,PRIM_ASSIGN_LOC_CD INT
		,LOG_ACCESS_IND INT
		,LOG_LEVEL INT
		,NAME_LAST_KEY_NLS VARCHAR(202)
		,NAME_FIRST_KEY_NLS VARCHAR(202)
		,PHYSICIAN_STATUS_CD INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,CREATE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,LOGICAL_DOMAIN_GRP_ID INT
		,LOGICAL_DOMAIN_ID INT
		,NAME_FIRST_KEY_A_NLS VARCHAR(400)
		,NAME_LAST_KEY_A_NLS VARCHAR(400)
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)
	
	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #prsnl_update
	EXEC('
	select
		PERSON_ID
		,UPDT_CNT
		,UPDT_DT_TM
		,UPDT_ID
		,UPDT_TASK
		,UPDT_APPLCTX
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,CREATE_PRSNL_ID
		,NAME_LAST_KEY
		,NAME_FIRST_KEY
		,PRSNL_TYPE_CD
		,NAME_FULL_FORMATTED
		,PASSWORD
		,EMAIL
		,PHYSICIAN_IND
		,POSITION_CD
		,DEPARTMENT_CD
		,FREE_TEXT_IND
		,SECTION_CD
		,DATA_STATUS_CD
		,DATA_STATUS_PRSNL_ID
		,CONTRIBUTOR_SYSTEM_CD
		,NAME_LAST
		,NAME_FIRST
		,USERNAME
		,FT_ENTITY_NAME
		,FT_ENTITY_ID
		,PRIM_ASSIGN_LOC_CD
		,LOG_ACCESS_IND
		,LOG_LEVEL
		,NAME_LAST_KEY_NLS
		,NAME_FIRST_KEY_NLS
		,PHYSICIAN_STATUS_CD
		,ACTIVE_STATUS_DT_TM
		,BEG_EFFECTIVE_DT_TM
		,CREATE_DT_TM
		,DATA_STATUS_DT_TM
		,END_EFFECTIVE_DT_TM
		,LOGICAL_DOMAIN_GRP_ID
		,LOGICAL_DOMAIN_ID
		,NAME_FIRST_KEY_A_NLS
		,NAME_LAST_KEY_A_NLS
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		prsnl
	where
		(create_dt_tm >= ? and create_dt_tm < ?)
		OR (updt_dt_tm >= ? and updt_dt_tm < ?)
	', @StartDate, @EndDate, @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	CREATE TABLE #prsnl_update_filtered (
		PERSON_ID INT
		,UPDT_CNT INT
		,UPDT_DT_TM DATETIME2
		,UPDT_ID INT
		,UPDT_TASK INT
		,UPDT_APPLCTX INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,CREATE_PRSNL_ID INT
		,NAME_LAST_KEY VARCHAR(100)
		,NAME_FIRST_KEY VARCHAR(100)
		,PRSNL_TYPE_CD INT
		,NAME_FULL_FORMATTED VARCHAR(100)
		,PASSWORD VARCHAR(100)
		,EMAIL VARCHAR(100)
		,PHYSICIAN_IND INT
		,POSITION_CD INT
		,DEPARTMENT_CD INT
		,FREE_TEXT_IND INT
		,SECTION_CD INT
		,DATA_STATUS_CD INT
		,DATA_STATUS_PRSNL_ID INT
		,CONTRIBUTOR_SYSTEM_CD INT
		,NAME_LAST VARCHAR(200)
		,NAME_FIRST VARCHAR(200)
		,USERNAME VARCHAR(50)
		,FT_ENTITY_NAME VARCHAR(32)
		,FT_ENTITY_ID INT
		,PRIM_ASSIGN_LOC_CD INT
		,LOG_ACCESS_IND INT
		,LOG_LEVEL INT
		,NAME_LAST_KEY_NLS VARCHAR(202)
		,NAME_FIRST_KEY_NLS VARCHAR(202)
		,PHYSICIAN_STATUS_CD INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,CREATE_DT_TM DATETIME2
		,DATA_STATUS_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,LOGICAL_DOMAIN_GRP_ID INT
		,LOGICAL_DOMAIN_ID INT
		,NAME_FIRST_KEY_A_NLS VARCHAR(400)
		,NAME_LAST_KEY_A_NLS VARCHAR(400)
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #prsnl_update_filtered
	select
		pu.PERSON_ID
		,pu.UPDT_CNT
		,pu.UPDT_DT_TM
		,pu.UPDT_ID
		,pu.UPDT_TASK
		,pu.UPDT_APPLCTX
		,pu.ACTIVE_IND
		,pu.ACTIVE_STATUS_CD
		,pu.ACTIVE_STATUS_PRSNL_ID
		,pu.CREATE_PRSNL_ID
		,pu.NAME_LAST_KEY
		,pu.NAME_FIRST_KEY
		,pu.PRSNL_TYPE_CD
		,pu.NAME_FULL_FORMATTED
		,pu.PASSWORD
		,pu.EMAIL
		,pu.PHYSICIAN_IND
		,pu.POSITION_CD
		,pu.DEPARTMENT_CD
		,pu.FREE_TEXT_IND
		,pu.SECTION_CD
		,pu.DATA_STATUS_CD
		,pu.DATA_STATUS_PRSNL_ID
		,pu.CONTRIBUTOR_SYSTEM_CD
		,pu.NAME_LAST
		,pu.NAME_FIRST
		,pu.USERNAME
		,pu.FT_ENTITY_NAME
		,pu.FT_ENTITY_ID
		,pu.PRIM_ASSIGN_LOC_CD
		,pu.LOG_ACCESS_IND
		,pu.LOG_LEVEL
		,pu.NAME_LAST_KEY_NLS
		,pu.NAME_FIRST_KEY_NLS
		,pu.PHYSICIAN_STATUS_CD
		,pu.ACTIVE_STATUS_DT_TM
		,pu.BEG_EFFECTIVE_DT_TM
		,pu.CREATE_DT_TM
		,pu.DATA_STATUS_DT_TM
		,pu.END_EFFECTIVE_DT_TM
		,pu.LOGICAL_DOMAIN_GRP_ID
		,pu.LOGICAL_DOMAIN_ID
		,pu.NAME_FIRST_KEY_A_NLS
		,pu.NAME_LAST_KEY_A_NLS
		,pu.ENTERPRISE_UPDATE_DT_TM
	from
		#prsnl_update pu
		left outer join cerner.PRSNL p on p.PERSON_ID = pu.PERSON_ID
	where
		p.PERSON_ID is null
	union all
	select
		pu.PERSON_ID
		,pu.UPDT_CNT
		,pu.UPDT_DT_TM
		,pu.UPDT_ID
		,pu.UPDT_TASK
		,pu.UPDT_APPLCTX
		,pu.ACTIVE_IND
		,pu.ACTIVE_STATUS_CD
		,pu.ACTIVE_STATUS_PRSNL_ID
		,pu.CREATE_PRSNL_ID
		,pu.NAME_LAST_KEY
		,pu.NAME_FIRST_KEY
		,pu.PRSNL_TYPE_CD
		,pu.NAME_FULL_FORMATTED
		,pu.PASSWORD
		,pu.EMAIL
		,pu.PHYSICIAN_IND
		,pu.POSITION_CD
		,pu.DEPARTMENT_CD
		,pu.FREE_TEXT_IND
		,pu.SECTION_CD
		,pu.DATA_STATUS_CD
		,pu.DATA_STATUS_PRSNL_ID
		,pu.CONTRIBUTOR_SYSTEM_CD
		,pu.NAME_LAST
		,pu.NAME_FIRST
		,pu.USERNAME
		,pu.FT_ENTITY_NAME
		,pu.FT_ENTITY_ID
		,pu.PRIM_ASSIGN_LOC_CD
		,pu.LOG_ACCESS_IND
		,pu.LOG_LEVEL
		,pu.NAME_LAST_KEY_NLS
		,pu.NAME_FIRST_KEY_NLS
		,pu.PHYSICIAN_STATUS_CD
		,pu.ACTIVE_STATUS_DT_TM
		,pu.BEG_EFFECTIVE_DT_TM
		,pu.CREATE_DT_TM
		,pu.DATA_STATUS_DT_TM
		,pu.END_EFFECTIVE_DT_TM
		,pu.LOGICAL_DOMAIN_GRP_ID
		,pu.LOGICAL_DOMAIN_ID
		,pu.NAME_FIRST_KEY_A_NLS
		,pu.NAME_LAST_KEY_A_NLS
		,pu.ENTERPRISE_UPDATE_DT_TM
	from
		#prsnl_update pu
		left outer join cerner.PRSNL p on p.PERSON_ID = pu.PERSON_ID and p.UPDT_CNT < pu.UPDT_CNT
	where
		p.PERSON_ID is not null
END
		
BEGIN
	delete 
	from 
		cerner.PRSNL
	where 
		PERSON_ID in (select PERSON_ID from #prsnl_update_filtered)
END

BEGIN
	insert into cerner.PRSNL
	select * from #prsnl_update_filtered
END
