USE [ENTERPRISE]
GO
/****** Object:  StoredProcedure [cerner].[SCH_APPT_UPDATE]    Script Date: 11/29/2021 5:23:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [cerner].[SCH_APPT_UPDATE] AS

BEGIN
	create table #sch_appt_update (
		SCH_APPT_ID INT
		,RESOURCE_CD INT
		,PERSON_ID INT
		,SERVICE_RESOURCE_CD INT
		,DURATION INT
		,ACTIVITY_CD INT
		,ACTIVITY_MEANING VARCHAR(12)
		,TIME_TYPE_FLAG INT
		,SLOT_TYPE_ID INT
		,SLOT_STATE_CD INT
		,SLOT_STATE_MEANING VARCHAR(12)
		,SLOT_MNEMONIC VARCHAR(100)
		,SLOT_SCHEME_ID INT
		,DESCRIPTION VARCHAR(255)
		,CONTIGUOUS_IND INT
		,APPLY_LIST_ID INT
		,DEF_SLOT_ID INT
		,APPLY_SLOT_ID INT
		,APPT_SCHEME_ID INT
		,SCH_STATE_CD INT
		,STATE_MEANING VARCHAR(12)
		,SCH_ROLE_CD INT
		,ROLE_MEANING VARCHAR(12)
		,PRIMARY_ROLE_IND INT
		,SCH_EVENT_ID INT
		,SCHEDULE_SEQ INT
		,SCHEDULE_ID INT
		,BOOKING_ID INT
		,ENCNTR_ID INT
		,CANDIDATE_ID INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,UPDT_DT_TM DATETIME2
		,UPDT_APPLCTX INT
		,UPDT_ID INT
		,UPDT_CNT INT
		,UPDT_TASK INT
		,LIST_ROLE_ID INT
		,DEFINING_IND INT
		,ROLE_SEQ INT
		,ROLE_DESCRIPTION VARCHAR(200)
		,BIT_MASK INT
		,WARN_BIT_MASK INT
		,APPT_LOCATION_CD INT
		,SCH_TYPE_ID INT
		,SETUP_DURATION INT
		,ALERT_BIT_MASK INT
		,APPLY_DEF_ID INT
		,CLEANUP_DURATION INT
		,EXCLUDE_IND INT
		,HOLIDAY_WEEKEND_FLAG INT
		,BORDER_STYLE INT
		,BORDER_SIZE INT
		,BORDER_COLOR INT
		,SHAPE INT
		,PEN_SHAPE INT
		,GRPSESSION_ID INT
		,REFERRING_ORG_ID INT
		,ALLOCATED_PRSNL_ID INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_DT_TM DATETIME2
		,NULL_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,SLOT_VIS_BEG_DT_TM DATETIME2
		,END_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,ORIG_BEG_DT_TM DATETIME2
		,ORIG_END_DT_TM DATETIME2
		,SLOT_VIS_END_DT_TM DATETIME2
		,VERSION_DT_TM DATETIME2
		,VIS_BEG_DT_TM DATETIME2
		,VIS_END_DT_TM DATETIME2
		,SCH_DATE_APPLY_ID INT
		,RESERVE_RELEASE_DT_TM DATETIME2
		,GROUP_SLOT_LINK_VALUE INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)
	
	DECLARE @StartDate datetime2
	DECLARE @EndDate datetime2
	SET @StartDate = dateadd(day,-2,convert(date,getdate()))
	SET @EndDate = convert(date,getdate())

	INSERT INTO #sch_appt_update
	EXEC('
	select
		SCH_APPT_ID
		,RESOURCE_CD
		,PERSON_ID
		,SERVICE_RESOURCE_CD
		,DURATION
		,ACTIVITY_CD
		,ACTIVITY_MEANING
		,TIME_TYPE_FLAG
		,SLOT_TYPE_ID
		,SLOT_STATE_CD
		,SLOT_STATE_MEANING
		,SLOT_MNEMONIC
		,SLOT_SCHEME_ID
		,DESCRIPTION
		,CONTIGUOUS_IND
		,APPLY_LIST_ID
		,DEF_SLOT_ID
		,APPLY_SLOT_ID
		,APPT_SCHEME_ID
		,SCH_STATE_CD
		,STATE_MEANING
		,SCH_ROLE_CD
		,ROLE_MEANING
		,PRIMARY_ROLE_IND
		,SCH_EVENT_ID
		,SCHEDULE_SEQ
		,SCHEDULE_ID
		,BOOKING_ID
		,ENCNTR_ID
		,CANDIDATE_ID
		,ACTIVE_IND
		,ACTIVE_STATUS_CD
		,ACTIVE_STATUS_PRSNL_ID
		,UPDT_DT_TM
		,UPDT_APPLCTX
		,UPDT_ID
		,UPDT_CNT
		,UPDT_TASK
		,LIST_ROLE_ID
		,DEFINING_IND
		,ROLE_SEQ
		,ROLE_DESCRIPTION
		,BIT_MASK
		,WARN_BIT_MASK
		,APPT_LOCATION_CD
		,SCH_TYPE_ID
		,SETUP_DURATION
		,ALERT_BIT_MASK
		,APPLY_DEF_ID
		,CLEANUP_DURATION
		,EXCLUDE_IND
		,HOLIDAY_WEEKEND_FLAG
		,BORDER_STYLE
		,BORDER_SIZE
		,BORDER_COLOR
		,SHAPE
		,PEN_SHAPE
		,GRPSESSION_ID
		,REFERRING_ORG_ID
		,ALLOCATED_PRSNL_ID
		,ACTIVE_STATUS_DT_TM
		,BEG_DT_TM
		,NULL_DT_TM
		,BEG_EFFECTIVE_DT_TM
		,SLOT_VIS_BEG_DT_TM
		,END_DT_TM
		,END_EFFECTIVE_DT_TM
		,ORIG_BEG_DT_TM
		,ORIG_END_DT_TM
		,SLOT_VIS_END_DT_TM
		,VERSION_DT_TM
		,VIS_BEG_DT_TM
		,VIS_END_DT_TM
		,SCH_DATE_APPLY_ID
		,RESERVE_RELEASE_DT_TM
		,GROUP_SLOT_LINK_VALUE
		,sysdate as ENTERPRISE_UPDATE_DT_TM
	from
		sch_appt
	where
		(updt_dt_tm >= ? and updt_dt_tm < ?)
	', @StartDate, @EndDate) AT [CERNERPROD]
END

BEGIN
	create table #sch_appt_update_filtered (
		SCH_APPT_ID INT
		,RESOURCE_CD INT
		,PERSON_ID INT
		,SERVICE_RESOURCE_CD INT
		,DURATION INT
		,ACTIVITY_CD INT
		,ACTIVITY_MEANING VARCHAR(12)
		,TIME_TYPE_FLAG INT
		,SLOT_TYPE_ID INT
		,SLOT_STATE_CD INT
		,SLOT_STATE_MEANING VARCHAR(12)
		,SLOT_MNEMONIC VARCHAR(100)
		,SLOT_SCHEME_ID INT
		,DESCRIPTION VARCHAR(255)
		,CONTIGUOUS_IND INT
		,APPLY_LIST_ID INT
		,DEF_SLOT_ID INT
		,APPLY_SLOT_ID INT
		,APPT_SCHEME_ID INT
		,SCH_STATE_CD INT
		,STATE_MEANING VARCHAR(12)
		,SCH_ROLE_CD INT
		,ROLE_MEANING VARCHAR(12)
		,PRIMARY_ROLE_IND INT
		,SCH_EVENT_ID INT
		,SCHEDULE_SEQ INT
		,SCHEDULE_ID INT
		,BOOKING_ID INT
		,ENCNTR_ID INT
		,CANDIDATE_ID INT
		,ACTIVE_IND INT
		,ACTIVE_STATUS_CD INT
		,ACTIVE_STATUS_PRSNL_ID INT
		,UPDT_DT_TM DATETIME2
		,UPDT_APPLCTX INT
		,UPDT_ID INT
		,UPDT_CNT INT
		,UPDT_TASK INT
		,LIST_ROLE_ID INT
		,DEFINING_IND INT
		,ROLE_SEQ INT
		,ROLE_DESCRIPTION VARCHAR(200)
		,BIT_MASK INT
		,WARN_BIT_MASK INT
		,APPT_LOCATION_CD INT
		,SCH_TYPE_ID INT
		,SETUP_DURATION INT
		,ALERT_BIT_MASK INT
		,APPLY_DEF_ID INT
		,CLEANUP_DURATION INT
		,EXCLUDE_IND INT
		,HOLIDAY_WEEKEND_FLAG INT
		,BORDER_STYLE INT
		,BORDER_SIZE INT
		,BORDER_COLOR INT
		,SHAPE INT
		,PEN_SHAPE INT
		,GRPSESSION_ID INT
		,REFERRING_ORG_ID INT
		,ALLOCATED_PRSNL_ID INT
		,ACTIVE_STATUS_DT_TM DATETIME2
		,BEG_DT_TM DATETIME2
		,NULL_DT_TM DATETIME2
		,BEG_EFFECTIVE_DT_TM DATETIME2
		,SLOT_VIS_BEG_DT_TM DATETIME2
		,END_DT_TM DATETIME2
		,END_EFFECTIVE_DT_TM DATETIME2
		,ORIG_BEG_DT_TM DATETIME2
		,ORIG_END_DT_TM DATETIME2
		,SLOT_VIS_END_DT_TM DATETIME2
		,VERSION_DT_TM DATETIME2
		,VIS_BEG_DT_TM DATETIME2
		,VIS_END_DT_TM DATETIME2
		,SCH_DATE_APPLY_ID INT
		,RESERVE_RELEASE_DT_TM DATETIME2
		,GROUP_SLOT_LINK_VALUE INT
		,ENTERPRISE_UPDATE_DT_TM DATETIME2
	)

	INSERT INTO #sch_appt_update_filtered
	select
		su.SCH_APPT_ID
		,su.RESOURCE_CD
		,su.PERSON_ID
		,su.SERVICE_RESOURCE_CD
		,su.DURATION
		,su.ACTIVITY_CD
		,su.ACTIVITY_MEANING
		,su.TIME_TYPE_FLAG
		,su.SLOT_TYPE_ID
		,su.SLOT_STATE_CD
		,su.SLOT_STATE_MEANING
		,su.SLOT_MNEMONIC
		,su.SLOT_SCHEME_ID
		,su.DESCRIPTION
		,su.CONTIGUOUS_IND
		,su.APPLY_LIST_ID
		,su.DEF_SLOT_ID
		,su.APPLY_SLOT_ID
		,su.APPT_SCHEME_ID
		,su.SCH_STATE_CD
		,su.STATE_MEANING
		,su.SCH_ROLE_CD
		,su.ROLE_MEANING
		,su.PRIMARY_ROLE_IND
		,su.SCH_EVENT_ID
		,su.SCHEDULE_SEQ
		,su.SCHEDULE_ID
		,su.BOOKING_ID
		,su.ENCNTR_ID
		,su.CANDIDATE_ID
		,su.ACTIVE_IND
		,su.ACTIVE_STATUS_CD
		,su.ACTIVE_STATUS_PRSNL_ID
		,su.UPDT_DT_TM
		,su.UPDT_APPLCTX
		,su.UPDT_ID
		,su.UPDT_CNT
		,su.UPDT_TASK
		,su.LIST_ROLE_ID
		,su.DEFINING_IND
		,su.ROLE_SEQ
		,su.ROLE_DESCRIPTION
		,su.BIT_MASK
		,su.WARN_BIT_MASK
		,su.APPT_LOCATION_CD
		,su.SCH_TYPE_ID
		,su.SETUP_DURATION
		,su.ALERT_BIT_MASK
		,su.APPLY_DEF_ID
		,su.CLEANUP_DURATION
		,su.EXCLUDE_IND
		,su.HOLIDAY_WEEKEND_FLAG
		,su.BORDER_STYLE
		,su.BORDER_SIZE
		,su.BORDER_COLOR
		,su.SHAPE
		,su.PEN_SHAPE
		,su.GRPSESSION_ID
		,su.REFERRING_ORG_ID
		,su.ALLOCATED_PRSNL_ID
		,su.ACTIVE_STATUS_DT_TM
		,su.BEG_DT_TM
		,su.NULL_DT_TM
		,su.BEG_EFFECTIVE_DT_TM
		,su.SLOT_VIS_BEG_DT_TM
		,su.END_DT_TM
		,su.END_EFFECTIVE_DT_TM
		,su.ORIG_BEG_DT_TM
		,su.ORIG_END_DT_TM
		,su.SLOT_VIS_END_DT_TM
		,su.VERSION_DT_TM
		,su.VIS_BEG_DT_TM
		,su.VIS_END_DT_TM
		,su.SCH_DATE_APPLY_ID
		,su.RESERVE_RELEASE_DT_TM
		,su.GROUP_SLOT_LINK_VALUE
		,su.ENTERPRISE_UPDATE_DT_TM
	from
		#sch_appt_update su
		left outer join cerner.SCH_APPT s on s.SCH_APPT_ID = su.SCH_APPT_ID
	where
		s.SCH_APPT_ID is null
	union all
	select
		su.SCH_APPT_ID
		,su.RESOURCE_CD
		,su.PERSON_ID
		,su.SERVICE_RESOURCE_CD
		,su.DURATION
		,su.ACTIVITY_CD
		,su.ACTIVITY_MEANING
		,su.TIME_TYPE_FLAG
		,su.SLOT_TYPE_ID
		,su.SLOT_STATE_CD
		,su.SLOT_STATE_MEANING
		,su.SLOT_MNEMONIC
		,su.SLOT_SCHEME_ID
		,su.DESCRIPTION
		,su.CONTIGUOUS_IND
		,su.APPLY_LIST_ID
		,su.DEF_SLOT_ID
		,su.APPLY_SLOT_ID
		,su.APPT_SCHEME_ID
		,su.SCH_STATE_CD
		,su.STATE_MEANING
		,su.SCH_ROLE_CD
		,su.ROLE_MEANING
		,su.PRIMARY_ROLE_IND
		,su.SCH_EVENT_ID
		,su.SCHEDULE_SEQ
		,su.SCHEDULE_ID
		,su.BOOKING_ID
		,su.ENCNTR_ID
		,su.CANDIDATE_ID
		,su.ACTIVE_IND
		,su.ACTIVE_STATUS_CD
		,su.ACTIVE_STATUS_PRSNL_ID
		,su.UPDT_DT_TM
		,su.UPDT_APPLCTX
		,su.UPDT_ID
		,su.UPDT_CNT
		,su.UPDT_TASK
		,su.LIST_ROLE_ID
		,su.DEFINING_IND
		,su.ROLE_SEQ
		,su.ROLE_DESCRIPTION
		,su.BIT_MASK
		,su.WARN_BIT_MASK
		,su.APPT_LOCATION_CD
		,su.SCH_TYPE_ID
		,su.SETUP_DURATION
		,su.ALERT_BIT_MASK
		,su.APPLY_DEF_ID
		,su.CLEANUP_DURATION
		,su.EXCLUDE_IND
		,su.HOLIDAY_WEEKEND_FLAG
		,su.BORDER_STYLE
		,su.BORDER_SIZE
		,su.BORDER_COLOR
		,su.SHAPE
		,su.PEN_SHAPE
		,su.GRPSESSION_ID
		,su.REFERRING_ORG_ID
		,su.ALLOCATED_PRSNL_ID
		,su.ACTIVE_STATUS_DT_TM
		,su.BEG_DT_TM
		,su.NULL_DT_TM
		,su.BEG_EFFECTIVE_DT_TM
		,su.SLOT_VIS_BEG_DT_TM
		,su.END_DT_TM
		,su.END_EFFECTIVE_DT_TM
		,su.ORIG_BEG_DT_TM
		,su.ORIG_END_DT_TM
		,su.SLOT_VIS_END_DT_TM
		,su.VERSION_DT_TM
		,su.VIS_BEG_DT_TM
		,su.VIS_END_DT_TM
		,su.SCH_DATE_APPLY_ID
		,su.RESERVE_RELEASE_DT_TM
		,su.GROUP_SLOT_LINK_VALUE
		,su.ENTERPRISE_UPDATE_DT_TM
	from
		#sch_appt_update su
		left outer join cerner.SCH_APPT s on s.SCH_APPT_ID = su.SCH_APPT_ID and s.UPDT_CNT < su.UPDT_CNT
	where
		s.SCH_APPT_ID is not null
END
		
BEGIN
	delete 
	from 
		cerner.SCH_APPT
	where 
		SCH_APPT_ID in (select SCH_APPT_ID from #sch_appt_update_filtered)
END

BEGIN
	insert into cerner.SCH_APPT
	select * from #sch_appt_update_filtered
END